### PR TITLE
`CreatePrecompileSuite` fixed E2E tests 

### LINKED ISSUE #9372: Fix E2E tests in CreatePrecompileSuite
Fix E2E tests in `CreatePrecompileSuite`

### PR DESCRIPTION
**Pull request by agadzhalov**
**Description**:
Fixes all suite tests in `CreatePrecompileSuite`

**Notes for reviewer**:
1. Please take a closer look at mono [handleSentHbars()](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/TokenCreatePrecompile.java#L409) implementation for the case with `INSUFFICIENT_TX_FEE`
2. The TODO comment for extracting `externalizeResult()` common logic will be addressed in another PR

**Related issue(s)**:

Fixes #9372

### CODE REVIEW

**Review by petreze — DISMISSED** [review]

**Review by tinker-michaelj — DISMISSED** [review]
Nice work @agadzhalov ! Once [this PR](https://github.com/hashgraph/hedera-services/pull/9649) is merged, the `MessageFrame` will be passed into `HtsCall.execute()` and it will be redundant to inject `value` and `blockValues` into `ClassicCreatesCall`.

But we can clean that up later. LGTM!

**Comment by agadzhalov** [comment]
> Nice work @agadzhalov ! Once [this PR](https://github.com/hashgraph/hedera-services/pull/9649) is merged, the `MessageFrame` will be passed into `HtsCall.execute()` and it will be redundant to inject `value` and `blockValues` into `ClassicCreatesCall`.
> 
> But we can clean that up later. LGTM!

Good to know, created a [ticket](https://github.com/hashgraph/hedera-services/issues/9797) to keep track.

**Review by dikel — DISMISSED** [review]

**Review by stoyanov-st — COMMENTED** [review]
Good job! I would suggest that you add more X tests to reflect on the unsuccessful responses.

**Comment by agadzhalov** [comment]
@stoyanov-st thank you. The tests will be added in a separate issue.

**Review by tinker-michaelj — APPROVED** [review]
Nice work @agadzhalov , tyvm!

**Review by MiroslavGatsanoga — APPROVED** [review]

**Pull request merged**
