### PR TITLE
[virtual_nfts] [1] Add configurable bootstrap property "tokens.nfts.useVirtualMerkle"

### PR DESCRIPTION
**Pull request by rjuang**
Adds configurable bootstrap property "tokens.nft.useVirtualMerkle" (default: disabled) that can be enabled to virtualize NFTs. Currently, this does nothing. This is a part of a series of PRs for virtualizing NFTs in a configurable manner.

Related issue: #3089

### CODE REVIEW

**Comment by rjuang** [comment]
@Neeharika-Sompalli can you advise whether I should make this bootstrap property string a constant ?

**Comment by Neeharika-Sompalli** [comment]
> @Neeharika-Sompalli can you advise whether I should make this bootstrap property string a constant ?

@rjuang , Yes please. Will be merging this [PR](https://github.com/hashgraph/hedera-services/pull/3809) that changes all properties to constants. Thanks !

**Review by tinker-michaelj — APPROVED** [review]
LGTM!

**Review by tinker-michaelj — APPROVED** [review]
LGTM

**Pull request merged**
