### PR TITLE
fix: support restarting from `RECORDS` -> `BOTH`

### LINKED ISSUE #15899: `BlockStreamInfo` migration logic needs to run in a `Schema` of the latest version
### Description

Putting the `BlockStreamInfo` migration in a 0.54 `Schema` [here](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/schemas/V0540BlockStreamSchema.java#L84) assumes we are enabling a non-`RECORDS` stream mode in 0.55, which is not true.

Instead we need a `Schema` dedicated to doing this migration which uses an idempotent `restart()` override to guarantee `BlockStreamInfo` is always initialized.

### Steps to reproduce

As above.

### Additional context

_No response_

### Hedera network

other

### Version

develop

### Operating system

None

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Description**:
 - Fixes #15899

### CODE REVIEW

**Review by derektriley — APPROVED** [review]
LGTM. Although I can't load/see the new Codacy issues.

**Review by petreze — APPROVED** [review]

**Comment by andrewb1269hg** [comment]
Please review the Codacy findings before merging.

**Comment by mhess-swl** [comment]
> Please review the Codacy findings before merging.

Codacy hasn't yet been tuned to a useful rule set. It frequently complains about issues that aren't issues. I'm not sure why it's running at all at this point.

**Comment by tinker-michaelj** [comment]
> Please review the Codacy findings before merging.

Reviewed and these findings are not actionable given our repo conventions, thx @andrewb1269hg !

**Pull request merged**
