### PR TITLE
fix: reflect auto-association fees in gas cost of transfer system contracts

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Description**:
 - Cherry-pick #14292

### CODE REVIEW

**Review by david-bakin-sl — DISMISSED** [review]
Cherry-pick LGTM.

**Review by Neeharika-Sompalli — DISMISSED** [review]
LGTM! Thanks @tinker-michaelj

**Review by david-bakin-sl — DISMISSED** [review]
This is not a trivial cherry-pick - a merge was apparently necessary.  A check against a config setting was added.  And a brand new BDD as well.  But it all checks out, according to me.

LGTM.

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM! Thanks @tinker-michaelj

**Review by Neeharika-Sompalli — APPROVED** [review]

**Review by david-bakin-sl — APPROVED** [review]
LGTM (as above)

**Pull request merged**
