### PR TITLE
Use Helidon for gRPC in mono service

### LINKED ISSUE #6981: Update mono service to use Helidon instead of Netty
Helidon works better in a modular environment. Right now we have two versions of gRPC libraries. Consolidating on Helidon will give us a modular grpc server.

### PR DESCRIPTION
**Pull request by rbair23**
Closes #6981 

Replaces direct setup of gRPC on Netty with setup of gRPC on Helidon (which in turn is using Netty). Netty does not play well with modularity, while Helidon does (they made necessary changes to modularize gRPC / Netty). This PR does not represent the last step, we want to bring epoll back in, and we also need to look at bringing other settings over in another PR, along with performance testing.

### CODE REVIEW

**Review by jsync-swirlds — APPROVED** [review]

**Comment by jsync-swirlds** [comment]
Good change.  We need to fix the validator for the log test, but the concurrent specs all finish within expected times, all the other integration tests succeed, and the unit and end-to-end tests all pass.

**Review by nathanklick — APPROVED** [review]

**Review by tinker-michaelj — APPROVED** [review]
LGTM! 🙏

**Review by qnswirlds — COMMENTED** [review]
As the `HelidonGrpcServerManager` replaces the `NettyGrpcServerManager`, the corresponding test suite should be replaced as well. The `NettyGrpcServerManagerTest` was deleted without a replacement. The `HelidonGrpcServerManager` was missing a few `final` keywords as well.

**Comment by jsync-swirlds** [comment]
> As the `HelidonGrpcServerManager` replaces the `NettyGrpcServerManager`, the corresponding test suite should be replaced as well. The `NettyGrpcServerManagerTest` was deleted without a replacement. The `HelidonGrpcServerManager` was missing a few `final` keywords as well.

Added to issue #6984 to be done tomorrow.

**Review by qnswirlds — APPROVED** [review]

**Pull request merged**
