### PR TITLE
chore: Fix compiler warnings in token service

### LINKED ISSUE #14693: Fix compiler warnings in hedera-token-service and hedera-token-service-impl

### PR DESCRIPTION
**Pull request by derektriley**
**Description**:

Fixes compiler warnings (exports ,lossy-conversions, static) in token service.

**Related issue(s)**: 

Fixes #14693

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by jjohannes — DISMISSED** [review]
👍 for the build.gradle change. Thanks.

**Review by mhess-swl — APPROVED** [review]

**Review by thomas-swirlds-labs — APPROVED** [review]
LGTM. Thanks! @derektriley

**Review by rbarkerSL — DISMISSED** [review]
LGTM

**Review by rbarkerSL — APPROVED** [review]
lgtm

**Review by mhess-swl — APPROVED** [review]

**Pull request merged**
