### PR TITLE
fix: Rename Versioned.getVersion() to getClassVersion()

### PR DESCRIPTION
**Pull request by Ndacyayisenga-droid**
**Description**:

**Related issue(s)**:

Fixes https://github.com/hashgraph/hedera-services/issues/5226

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by hendrikebbers — DISMISSED** [review]
LGTM

**Comment by hendrikebbers** [comment]
@poulok can you add a milestone to this one. It is a community contribution from hacktoberfest.

**Comment by jsync-swirlds** [comment]
@Ndacyayisenga-droid It looks like you tried to merge in the base branch, but that wasn't clean (and the result is an unverified commit). No amount of git merge can fix that issue as `merge` only adds to history; never rewrites.
Github won't allow a merge or this PR with that unverified commit, however.
_If possible_ you may want to consider using `git rebase` to squash this PR to a single commit at the HEAD of the base branch.

If a simple rebase proves difficult, the following process (performed in your fork) can provide a (more aggressive) alternative.
```
    git switch develop
    git remote add hashgraph git@github.com:hashgraph/hedera-services.git
    git rebase hashgraph/develop
    git push origin develop
    git switch 5226-rename-Versioned.getVersion-to-getClassVersion
    git reset $(git merge-base develop $(git branch --show-current))
    git add .
    git commit -sS
    git push --force origin 5226-rename-Versioned.getVersion-to-getClassVersion
```

**Comment by hendrikebbers** [comment]
new PR: https://github.com/hashgraph/hedera-services/pull/15992

**Pull request closed without merging**
