### PR TITLE
Implement TokenMintHandler prehandle

### LINKED ISSUE #4593: Implement `TokenMintHandler.preHandle()`

### PR DESCRIPTION
**Pull request by stoyan-lime**
**Description**:
* Adds the pre handle logic for token mint

**Related issue(s)**:

Fixes #4593

### CODE REVIEW

**Review by dimitar-dinev — APPROVED** [review]
LGTM!

**Comment by mhess-swl** [comment]
I don't see any tests ported from `SigRequirementsTest` to test this new code. We want to make sure we have the same functionality in both the new and old code.

**Comment by dimitar-dinev** [comment]
> I don't see any tests ported from `SigRequirementsTest` to test this new code. We want to make sure we have the same functionality in both the new and old code.

AFAICT, all of the scenarios from `TokenMintScenarios` (which are used in the tests from `SigRequirementsTest`) are being exercised in `TokenMintHandlerTest`. Are there any others that have been missed?

**Review by mhess-swl — APPROVED** [review]

**Comment by mhess-swl** [comment]
> > I don't see any tests ported from `SigRequirementsTest` to test this new code. We want to make sure we have the same functionality in both the new and old code.
> 
> AFAICT, all of the scenarios from `TokenMintScenarios` (which are used in the tests from `SigRequirementsTest`) are being exercised in `TokenMintHandlerTest`. Are there any others that have been missed?

Nope, I took a closer look and these look good. Thanks!

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM ! But, any tests that are being ported from `SigRequirementsTests` we are naming the file as `TokenMintHandlerParityTest`. We could follow the same pattern

**Pull request merged**
