### PR TITLE
Query fee calculation

### LINKED ISSUE #8543: Implement  feeCalculator in QueryContextImpl.java

### PR DESCRIPTION
**Pull request by netopyr**
Implementation of `FeeCalculator` for queries

Closes #8543

### CODE REVIEW

**Review by iwsimon — DISMISSED** [review]
LGTM

**Review by Neeharika-Sompalli — COMMENTED** [review]
Seems some HAPI tests are failing

**Comment by netopyr** [comment]
> Seems some HAPI tests are failing

Yes, that made me discover the unstable tests. The failures are unrelated to my changes.

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM !

**Pull request merged**
