### PR TITLE
Add validation for Token decimal info in TokenTransferList

### LINKED ISSUE #2735: HIP-31 : Add Token transfer decimal information to TokenTransferList
- [ ] Protobuf changes  https://github.com/hashgraph/hedera-protobufs/pull/127/files
- [ ] Add a check in `PureTransferSemanticChecks` to validate the `expected_decimals` to match the decimals of corresponding `Token` in token transfer `TransferList` . If it doesn't match throw `UNEXPECTED_TOKEN_DECIMALS`

### PR DESCRIPTION
**Pull request by Neeharika-Sompalli**
Closes #2735 
Related to [HIP-31](https://hips.hedera.com/hip/hip-31)

1. Added `expectedDecimals` to `BalanceChange` , which has default value as `-1` until it is explicitly set.
2. In `ImpliedTransfersMarshal` set the `decimals` to first balance change of the corresponding token
3. In `TokenStore.tryTokenChange()` validate if the decimals match. If not , return `UNEXPECTED_TOKEN_DECIMALS`

### CODE REVIEW

**Review by anighanta — APPROVED** [review]

**Review by tinker-michaelj — CHANGES_REQUESTED** [review]
In general, using a component like `TokenStore` in `PureTransferSemanticChecks` creates the possibility of an ISS, because `PureTransferSemanticChecks` is called during `expandSignatures()`. So it must not use any component that can change between `expandSignatures()` and `handleTransaction()` **UNLESS** it also double-checks in `handleTransaction()` that the component truly did not change.

(For example, like we do [here](https://github.com/hashgraph/hedera-services/blob/master/hedera-node/src/main/java/com/hedera/services/txns/span/SpanMapManager.java#L101) to make sure that any global/dynamic properties used during `expandSignatures()` didn't change.)

In this particular case, we can't get an ISS, because we're not checking if the token exists, so  `tokenStore.get(...).decimals()` will throw a `NullPointerException` if we are expanding for a `CryptoTransfer` that references a token that has not---quite yet!---been created. That NPE will propagate up to [here](https://github.com/hashgraph/hedera-services/blob/master/hedera-node/src/main/java/com/hedera/services/ServicesState.java#L195) and force this check to repeat in `handleTransaction()`, getting the correct answer.

Overall, I think the most natural approach for this HIP is to,
1. Add new `BalanceChange` fields `boolean hasExpectedDecimals` and `int expectedDecimals`.
2. In `ImpliedTransfersMarshal`, set these fields for the first `BalanceChange` in a `tokenTransfersList` that has expected decimals.
3. In `TokenStore.tryTokenChange()` [here](https://github.com/hashgraph/hedera-services/blob/1d2326af92ee368128c6253b704e7274a7ee111f/hedera-node/src/main/java/com/hedera/services/store/tokens/TokenStore.java#L106), if `change.hasExpectedDecimals()`, check if the expected decimals match the actual decimals and return `UNEXPECTED_TOKEN_DECIMALS` if so.

**Comment by Neeharika-Sompalli** [comment]
> In general, using a component like `TokenStore` in `PureTransferSemanticChecks` creates the possibility of an ISS, because `PureTransferSemanticChecks` is called during `expandSignatures()`. So it must not use any component that can change between `expandSignatures()` and `handleTransaction()` **UNLESS** it also double-checks in `handleTransaction()` that the component truly did not change.
> 
> (For example, like we do [here](https://github.com/hashgraph/hedera-services/blob/master/hedera-node/src/main/java/com/hedera/services/txns/span/SpanMapManager.java#L101) to make sure that any global/dynamic properties used during `expandSignatures()` didn't change.)
> 
> In this particular case, we can't get an ISS, because we're not checking if the token exists, so `tokenStore.get(...).decimals()` will throw a `NullPointerException` if we are expanding for a `CryptoTransfer` that references a token that has not---quite yet!---been created. That NPE will propagate up to [here](https://github.com/hashgraph/hedera-services/blob/master/hedera-node/src/main/java/com/hedera/services/ServicesState.java#L195) and force this check to repeat in `handleTransaction()`, getting the correct answer.
> 
> Overall, I think the most natural approach for this HIP is to,
> 
> 1. Add new `BalanceChange` fields `boolean hasExpectedDecimals` and `int expectedDecimals`.
> 2. In `ImpliedTransfersMarshal`, set these fields for the first `BalanceChange` in a `tokenTransfersList` that has expected decimals.
> 3. In `TokenStore.tryTokenChange()` [here](https://github.com/hashgraph/hedera-services/blob/1d2326af92ee368128c6253b704e7274a7ee111f/hedera-node/src/main/java/com/hedera/services/store/tokens/TokenStore.java#L106), if `change.hasExpectedDecimals()`, check if the expected decimals match the actual decimals and return `UNEXPECTED_TOKEN_DECIMALS` if so.

@tinker-michaelj  Thank you for the clear explanation. 😇  Modified to use the approach you mentioned. Please re-review when you are available.

**Review by tinker-michaelj — APPROVED** [review]
LGTM!

**Review by qnswirlds — COMMENTED** [review]
Sorry, I didn't get a chance to look at this PR until now. But it looks good to me! Thanks!

**Pull request merged**
