### PR TITLE
chore: remove property evm.version.dynamic

### LINKED ISSUE #12462: remove `contracts.evm.version.dynamic` property
### Problem

The `contracts.evm.version.dynamic` is not implemented in the modularized code.

### Solution

Implement a way to have dagger provided the correct EVM version update configuration update.

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by lukelee-sl**
**Description**:
Confirmed with folks working on reusable services in mirror node that this property is no longer needed.  It is not used in the modularized code base.
 
**Related issue(s)**:

Fixes #12462

### CODE REVIEW

**Review by david-bakin-sl — DISMISSED** [review]
Oddly, the doc `evm-versioning.md` refers to "when dynamic is set to {false|true}` in the "Acceptance Test" section ... even though it also says that switching it at runtime is a non-goal.

So, LGTM though for extra credit you could  eliminate those two lines under "Acceptance Tests" so as not to confuse anyone later ...

**Review by david-bakin-sl — APPROVED** [review]

**Review by kimbor — DISMISSED** [review]
lgtm!

**Comment by Nana-EC** [comment]
@lukelee-sl we can remove this for now as it's unused and revisit the correct approach if needed in the future

**Comment by lukelee-sl** [comment]
I had to rebase.  @kimbor , @david-bakin-sl - mind signing off again?

**Review by kimbor — APPROVED** [review]

**Review by david-bakin-sl — APPROVED** [review]
LGTM

**Review by Nana-EC — APPROVED** [review]
LG

**Pull request merged**
