### PR TITLE
Delete QueueThreadPool and related classes

### LINKED ISSUE #5471: Delete QueueThreadPool
`QueueThreadPool` is unused. Delete the following:

- `QueueThreadPool`
- `QueueThreadPoolImpl`
- `QueueThreadPoolConfiguration`
- `AbstractQueueThreadPoolConfiguration`
- `QueueThreadPoolTests`

Discussed with @cody-littley - this class never got used, so it's better to delete than have unused code floating around complicating things

### PR DESCRIPTION
**Pull request by alittley**
Resolves #5471 

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by cody-littley — APPROVED** [review]
I had high hopes for this feature, but since we never actually found a good use for it, better to remove it. Nothing worse than maintaining dead features.

**Comment by alittley** [comment]
> I had high hopes for this feature, but since we never actually found a good use for it, better to remove it. Nothing worse than maintaining dead features.

:( This was a big chunk of well considered feature to just delete... too bad

**Comment by lpetrovic05** [comment]
Are we sure this will never be useful? I can think of a use for it....

**Comment by alittley** [comment]
Potential use cases exist for this I wasn't aware of.

**Pull request closed without merging**
