### PR TITLE
Added newTotalSuppy in TransactionReceipt for token mint/burn/wipe transactions

### LINKED ISSUE #645: TokenMint, TokenBurn and TokenWipe should return the new totalSupply
**Summary**
~As a Hedera Services client, I need updates to the current Token Transaction bodies so that I can accomplish consuming Token details in a more compareable manner to crypto.~
Also updates(s) may be needed to allow mirror nodes to retrieve updated token total Supply after operations that modify it

**Possible resolution**
Below are some items that could be updated
- ~`TokenCreateTransactionBody` should return a Duration for `AutoRenewPeriod`, similar to `ConsensusCreateTopic`~ Fixed by #756
- ~`TokenCreateTransactionBody` should return a Timestamp for `Expiry`, similar to `ConsensusCreateTopic`~ Fixed by #756
- We should update the `TransactionReceipt` to include a `newTotalSupply` field which is set after the `TokenMint`, `TokenBurn` and `TokenWipe` operations reach consensus and resolve to a status of `SUCCESS`.

### PR DESCRIPTION
**Pull request by ljianghedera**
**Related issue(s)**:
Closes #645 

**Summary of the change**:
1. Added newTotalSupply in TransactionReceipt for Token mint/burn/wipe transactions if these these transactions are successful;

**External impacts**:
None.

**Applicable documentation**
- [ ] Javadoc
- [X] HAPI protobuf comments
- [ ] README

### CODE REVIEW

**Comment by ljianghedera** [comment]
I tried to remove the legacy Provider in TxnReceipt, but somehow I got several unit test failures from seemingly unrelated places. I couldn't find the relationship and fix, so I decided to leave the legacy Provider alone as it is. Hopefully this won't have any side impact.

**Review by tinker-michaelj — APPROVED** [review]
LGTM, nice work!

**Comment by tinker-michaelj** [comment]
> I tried to remove the legacy Provider in TxnReceipt, but somehow I got several unit test failures from seemingly unrelated places. I couldn't find the relationship and fix, so I decided to leave the legacy Provider alone as it is. Hopefully this won't have any side impact.

Nah, it's fine. We can have a dedicated issue to remove all the unused `SerializedObjectProvider` implementations. ⚡

**Comment by ljianghedera** [comment]
Yeah, anyway we will have issues to refactor the jproto packages.

**Pull request merged**
