### PR TITLE
Create JRS keys directory

### LINKED ISSUE #3266: Create JRS keys directory
After the following PR https://github.com/swirlds/swirlds-platform-regression/pull/2318, JRS keys directory was removed from the JRS repo together with the `keys/generateKeyPair.sh` script.

### PR DESCRIPTION
**Pull request by qnswirlds**
Close #3266

### CODE REVIEW

**Review by Neeharika-Sompalli — COMMENTED** [review]
Is the existing `keys` folder deleted ?

**Comment by qnswirlds** [comment]
> Is the existing `keys` folder in the repo deleted ?

Yes, please see details in #3266

**Comment by Neeharika-Sompalli** [comment]
> > Is the existing `keys` folder in the repo deleted ?
> 
> Yes, please see details in #3266

 Thanks @qnswirlds  ... Does it not cause an error when running JRS test from local (or does maven build create that directory)

**Comment by qnswirlds** [comment]
> > > Is the existing `keys` folder in the repo deleted ?
> > 
> > 
> > Yes, please see details in #3266
> 
> Thanks @qnswirlds ... Does it not cause an error when running JRS test from local (or does maven build create that directory)

No, for local, each dev should have a key location to provide to the CloudConfig (`cloud.keyLocation`). It just happens to usually be the same {JRS_keys_dir/yourKey.pem}, but deleting in the repo does not delete your local copy with untracked content (in this case yourKey.pem)

**Review by nathanklick — APPROVED** [review]

**Pull request merged**
