### PR TITLE
chore: Made StakingValidator static

### LINKED ISSUE #14127: Make StakingValidator static
The class `StakingValidator` has no internal state, and all methods can be turned into static methods. With this change, we would also not have to inject an instance.

### PR DESCRIPTION
**Pull request by HarshSawarkar**
**Description**:

The StakingValidator class doesn't have any internal state, and its methods can be turned into static to avoid injecting an instance.

**Related issue(s)**:

Fixes #14127 

**Notes for reviewer**:

Modified the usage classes of the StakingValidator.java class to use the static methods directly

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by netopyr — DISMISSED** [review]
LGTM - thanks @HarshSawarkar

**Comment by netopyr** [comment]
@HarshSawarkar 
Thanks for your contribution. I am looking forward to merging it soon. 😄 

The Spotless check failed during the build. (I will check if we need to update the documentation with this required step.) The easiest to pass this check is to run `./gradlew spotlessApply` which will reformat the code according to the guidelines.

**Comment by HarshSawarkar** [comment]
> @HarshSawarkar Thanks for your contribution. I am looking forward to merging it soon. 😄
> 
> The Spotless check failed during the build. (I will check if we need to update the documentation with this required step.) The easiest to pass this check is to run `./gradlew spotlessApply` which will reformat the code according to the guidelines.

I have made the necessary changes to ensure the build runs successfully. Thanks for your help, and I look forward to making more contributions in the future!

**Review by netopyr — APPROVED** [review]
LGTM - thanks @HarshSawarkar

**Pull request merged**
