### PR TITLE
fix: Cherry Pick of #12905 (double-count child staking rewards)

### PR DESCRIPTION
**Pull request by mhess-swl**
Cherry pick of PR #12905 to develop

### CODE REVIEW

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM !

**Review by thomas-swirlds-labs — APPROVED** [review]
LGTM. Thanks ! @mhess-swl

**Review by povolev15 — APPROVED** [review]

**Review by iwsimon — APPROVED** [review]
LGTM. Thanks @mhess-swl

**Comment by mhess-swl** [comment]
Node death parsing failure is due to the size of the file; tests all passed successfully.

**Pull request merged**
