### PR TITLE
Disable account balance exports

### PR DESCRIPTION
**Pull request by mhess-swl**
This is the same as PR #8265, but we're updating the `develop` branch. Since the platform version in `develop` is already a 0.42 version, we won't depend on the updated 0.41.1 platform code (yet - that code still needs to be ported to 0.42 versions of platform)

### CODE REVIEW

**Review by tinker-michaelj — APPROVED** [review]
LGTM!

**Comment by JeffreyDallas** [comment]
This would cause the failure of balance test

https://swirldslabs.slack.com/archives/C05CH6A8AMV/p1693410577731049

**Comment by mhess-swl** [comment]
> This would cause the failure of balance test
> 
> https://swirldslabs.slack.com/archives/C05CH6A8AMV/p1693410577731049

@JeffreyDallas it's my understanding that account balances are going to be turned off in release 0.42, so I suspect we need to delete this test. Whom do we need to verify with?

**Comment by JeffreyDallas** [comment]
> Since it is just a property, can we enable balance files just for this test until we find a better solution?
> 
> What is the main purpose of this test: making sure the balance was calculated correctly or measuring the performance?

It's for checking that balances are correct.
Yes, I will enable balance files property for the specific tests failed

**Review by JeffreyDallas — APPROVED** [review]

**Review by netopyr — APPROVED** [review]
LGTM

**Pull request merged**
