### PR TITLE
chore: Change develop to main for a main branch

### LINKED ISSUE #16807: Prepare migration of default branch from develop to main
## Background

The @hashgraph/devops-ci team is planning to change the default branch on hedera-services from `develop` to `main`. 

- We are targeting Friday, December 20th at 22:00 US Central time for the switch-over.

## Desired outcome

We need a branch that modifies all of the source code, github workflows, scripts, etc. within the hedera-services repository to be set up such that all references to `develop` are re-targets to `main`

### PR DESCRIPTION
**Pull request by mishomihov00**
**Description**:

Change develop to main for a main branch

**Related issue(s)**:

Fixes #16807 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Comment by andrewb1269hg** [comment]
There are many files in here that are changed but not related to the `develop` to `main` transition. I'm working on identifying all of those now so they can be removed.

**Review by artemananiev — APPROVED** [review]
Looks fine from platform-data perspective

**Comment by andrewb1269hg** [comment]
This PR has been moved to this effort instead: #17091

**Review by timo0 — APPROVED** [review]
Checked all 41 platform files owned by me. For some reason, only 3 files contained actual changes - all others had only unnecessary whitespace changes.

**Comment by andrewb1269hg** [comment]
This PR has been completed under #17091 instead. Closing this PR.

**Pull request closed without merging**
