### PR TITLE
Integrate Platform adhoc build 0.39.0-adhoc.xc2987c73 to services dev…

### LINKED ISSUE #6561: Integrate Platform adhoc build 0.39.0-adhoc.xc2987c73 to services develop
### Problem

Integrate Platform adhoc build 0.39.0-adhoc.xc2987c73 to services develop

### Solution

Integrate Platform adhoc build 0.39.0-adhoc.xc2987c73 to services develop

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by iwsimon**
**Description**:

Integrate Platform adhoc build

#6327 added breaking change from platform. 
NodeId.createMain->new NodeId(), NodeId.getId()->getIdAsInt(), NodeId(boolean, id)->NodeId(id).

**Related issue(s)**:

Fixes #6561 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Comment by jsync-swirlds** [comment]
Might want to add entries in .gitignore for the test files you removed (and a few others like them):
```
hedera-node/cli-clients/testFile
hedera-node/hedera-mono-service/src/test/resources/balance*/**
hedera-node/hedera-mono-service/temp/**
hedera-node/hedera-mono-service/swirlds-sst-tmp/**
```

**Review by hendrikebbers — DISMISSED** [review]

**Review by JeffreyDallas — APPROVED** [review]

**Review by kimbor — DISMISSED** [review]
There are a number of binary files in a swirlds-sst-tmp directory, these appear to have been checked in by mistake.

What is the purpose of the changes in VersionedConfigImpl? They don't appear to be related to the platform changes.

**Comment by iwsimon** [comment]
> There are a number of binary files in a swirlds-sst-tmp directory, these appear to have been checked in by mistake.
> 
> What is the purpose of the changes in VersionedConfigImpl? They don't appear to be related to the platform changes.

Change on VersionedConfigImpl is for compile the code.

**Comment by iwsimon** [comment]
> There are a number of binary files in a swirlds-sst-tmp directory, these appear to have been checked in by mistake.
> 
> What is the purpose of the changes in VersionedConfigImpl? They don't appear to be related to the platform changes.


Change on VersionedConfigImpl is for compile the code. I asked Hendrik reviewed this change.
Those binary files were removed from my branch. Will ask team to double check if they need to be removed such as in PR6508.

**Review by qnswirlds — APPROVED** [review]

**Review by mhess-swl — DISMISSED** [review]

**Review by mhess-swl — APPROVED** [review]

**Review by qnswirlds — APPROVED** [review]

**Review by kimbor — APPROVED** [review]

**Pull request merged**
