### PR TITLE
feat: Added 056 AddressBook schema

### LINKED ISSUE #16490: Add 056 AddressBook schema
Add 056 AddressBook schema to migrate the latest AddressBook info  since last migration was 0.53.

cherry-picked to release/0.56 PR #16528.

### PR DESCRIPTION
**Pull request by iwsimon**
**Description**:

**Related issue(s)**:

Fixes #16490 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by tinker-michaelj — COMMENTED** [review]
Since `develop` is 0.57, this schema's `migrate()` method will never run in production; did you intend to make its version `0.57.0`?

**Comment by netopyr** [comment]
> Since `develop` is 0.57, this schema's `migrate()` method will never run in production; did you intend to make its version `0.57.0`?

This change is also [cherry-picked](https://github.com/hashgraph/hedera-services/pull/16528) into the 0.56 release branch.

**Comment by iwsimon** [comment]
This is for 0.56 release. When DAB enabled, we can get the latest info migrated since last migration was 0.53. We should still merge this code to develop branch so we can keep on tracking all the previous schemas like other services.

**Review by tinker-michaelj — APPROVED** [review]
LGTM, ty @iwsimon !

**Pull request merged**
