### PR TITLE
Change swirlds.log format in log4j

### LINKED ISSUE #1035: Change the logging format of swirlds.log to match the format used in platform
**Summary**
Currently the logging format in `swirlds.log` logged in `hedera-services` is different from the format used in `swirlds-platform`. 

The new format has more details in the log compared to the previous one. Modify it to match the format used in platform, by modifying the log4j2.

In services the format used is 
```
      <PatternLayout pattern="%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p %-4L %c{1} - %m%n"/>
```

In platform the format used is 
```
			<PatternLayout>
				<pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} %-8sn %-5p %-16marker &lt;%t&gt; %c{1}: %msg%n</pattern>
			</PatternLayout>
```

- [x] Format should be modified in `hedera-node/configuration/` in all the folders `log4j2.xml` and for regression `swirlds-platform-regression/log4j2-services-regression.xml`
- [x] Also modify all the services JRS jsons to use to use `LogParserV3`  by changing `"swirldsLogVersion"` to 3
- [x]  Test all regression tests work well and could parse the new format

### PR DESCRIPTION
**Pull request by Neeharika-Sompalli**
**Related issue(s)**:
Closes #1035 

Related PR in regression :https://github.com/swirlds/swirlds-platform-regression/pull/873

Tests passed with the change:

1. Update : https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1613079545353000 **(Same as master)**
2. Migration : https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1613081129355600 **(Passed )**
3. Recovery : https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1613089189360400 **(same as master)**
4. Performance : Hotspot https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1613095640362400 **(Passed)**
5. Reconnect : 
6. NetError: https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1613078939351200 **(Failed as master)**
7. Restart: https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1613080144354100 **(Passed)**

### CODE REVIEW

**Review by ljianghedera — APPROVED** [review]
LGTM

**Review by JeffreyDallas — APPROVED** [review]

**Review by anighanta — APPROVED** [review]

**Review by qnswirlds — APPROVED** [review]
LGTM too! @jsindy, please help review and/or have other devops review this PR as well. Thank you!

**Review by tannerjfco — APPROVED** [review]
I tested this log format change in our integration environment and reviewed the output. This format change does not impact our freeze automation used in testing that reads the logs to determine when freeze occurs. Judging from the output I saw, I don't expect this to impact any of our log-based alerting, as we are generally looking for specific phrases or subset of a message rather than exact matches for a full log event line. So I think we are good to bring this in on our end.

We will however want to coordinate this merge with #1154 to ensure the new format change is present in the new preprod, testnet, previewnet, and mainnet configuration folders

**Comment by Neeharika-Sompalli** [comment]
> I tested this log format change in our integration environment and reviewed the output. This format change does not impact our freeze automation used in testing that reads the logs to determine when freeze occurs. Judging from the output I saw, I don't expect this to impact any of our log-based alerting, as we are generally looking for specific phrases or subset of a message rather than exact matches for a full log event line. So I think we are good to bring this in on our end.
> 
> We will however want to coordinate this merge with #1154 to ensure the new format change is present in the new preprod, testnet, previewnet, and mainnet configuration folders

Thanks @tannerjfco ! Once I merge this PR, I will merge back to #1154  and make sure they have correct logging format.

**Comment by anighanta** [comment]
> > I tested this log format change in our integration environment and reviewed the output. This format change does not impact our freeze automation used in testing that reads the logs to determine when freeze occurs. Judging from the output I saw, I don't expect this to impact any of our log-based alerting, as we are generally looking for specific phrases or subset of a message rather than exact matches for a full log event line. So I think we are good to bring this in on our end.
> > We will however want to coordinate this merge with #1154 to ensure the new format change is present in the new preprod, testnet, previewnet, and mainnet configuration folders
> 
> Thanks @tannerjfco ! Once I merge this PR, I will merge back to #1154 and make sure they have correct logging format.

I have updated PR #1154 accordingly :)

**Pull request merged**
