### PR TITLE
docs: Document the account sign tool

### LINKED ISSUE #14727: Document the account balance sign tool (Services CLI)

### PR DESCRIPTION
**Pull request by mhess-swl**
This PR adds documentation for the Services CLI account sign tool.

Closes #14727

### CODE REVIEW

**Review by iwsimon — COMMENTED** [review]
I used to run account balance sign with the follow command:
pcli account-balance sign private-aaaa.pfx "yourpassword" "keyalias" -d=signedAccountBalanceFiles -p=toBeSignedAccountBalanceFiles

**Comment by mhess-swl** [comment]
> I used to run account balance sign with the follow command: pcli account-balance sign private-aaaa.pfx "yourpassword" "keyalias" -d=signedAccountBalanceFiles -p=toBeSignedAccountBalanceFiles

@iwsimon ah, where should I update the documentation?

**Comment by iwsimon** [comment]
> > I used to run account balance sign with the follow command: pcli account-balance sign private-aaaa.pfx "yourpassword" "keyalias" -d=signedAccountBalanceFiles -p=toBeSignedAccountBalanceFiles
> 
> @iwsimon ah, where should I update the documentation?

It was in this pr https://github.com/hashgraph/hedera-services/pull/6264. It's good to create this document.

**Comment by mhess-swl** [comment]
> > > I used to run account balance sign with the follow command: pcli account-balance sign private-aaaa.pfx "yourpassword" "keyalias" -d=signedAccountBalanceFiles -p=toBeSignedAccountBalanceFiles
> > 
> > 
> > @iwsimon ah, where should I update the documentation?
> 
> It was in this pr #6264. It's good to create this document.

To clarify, what are you asking me to do? I can add a section about running with `pcli` if you'd like. Or, did you have something else in mind?

**Comment by iwsimon** [comment]
> > > > I used to run account balance sign with the follow command: pcli account-balance sign private-aaaa.pfx "yourpassword" "keyalias" -d=signedAccountBalanceFiles -p=toBeSignedAccountBalanceFiles
> > > 
> > > 
> > > @iwsimon ah, where should I update the documentation?
> > 
> > 
> > It was in this pr #6264. It's good to create this document.
> 
> To clarify, what are you asking me to do? I can add a section about running with `pcli` if you'd like. Or, did you have something else in mind?

Maybe just add this pcli command in the doc.

**Comment by mhess-swl** [comment]
> > > > > I used to run account balance sign with the follow command: pcli account-balance sign private-aaaa.pfx "yourpassword" "keyalias" -d=signedAccountBalanceFiles -p=toBeSignedAccountBalanceFiles
> > > > 
> > > > 
> > > > @iwsimon ah, where should I update the documentation?
> > > 
> > > 
> > > It was in this pr #6264. It's good to create this document.
> > 
> > 
> > To clarify, what are you asking me to do? I can add a section about running with `pcli` if you'd like. Or, did you have something else in mind?
> 
> Maybe just add this pcli command in the doc.

Cool, done!

**Review by iwsimon — APPROVED** [review]
LGTM. Thanks @mhess-swl

**Pull request merged**
