### PR TITLE
Standardized fee schedules w/ blessed Schedule* prices

### LINKED ISSUE #1122: Update fee schedules for v0.13.0 prices
**Summary**
The default _FeeSchedule.json_ should reflect up-to-date prices, especially so that CI tests can assert that "canonical" operations have the expected prices from https://docs.hedera.com/guides/mainnet/fees .

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Related issues**:
 - Closes #1122 

**Summary of the change**:
- With "canonical" consumption: `ScheduleCreate` price is ~1¢, `ScheduleSign` and `ScheduleDelete` prices are ~0.1¢.
- Canonical `CryptoCreate` is increased to ~5¢.
- Add `HapiTxnOp.feeUsd(double)` method to allow choosing a fee in USD.
- (+CI) Add `ScheduleRecordSpecs.canonicalScheduleOpsHaveExpectedUsdFees()` to assert schedule ops have expected prices.
- (+CI) Add `CryptoCreateSuite.usdFeeAsExpected()` to assert that 1¢ no longer sufficient and 5¢ is charged.
- Minor cleanup of an unused `HapiTxnOp.gas` field (contract ops manage their own gas config).

### CODE REVIEW

**Review by qnswirlds — COMMENTED** [review]
Because the fee for CryptoCreate is increased, I think it would be better to try creating an account with the old fee and expect `INSUFFICIENT_TX_FEE`.

**Review by Neeharika-Sompalli — APPROVED** [review]
Apart from having a negative test for CryptoCreate, rest LGTM

**Review by paulmadsenhed — DISMISSED** [review]
LGTM

**Review by Neeharika-Sompalli — APPROVED** [review]

**Review by qnswirlds — DISMISSED** [review]
LGTM! Thanks for adding more tests and enhancing the test framework!

**Pull request merged**
