### PR TITLE
chore: removing notnull annotations and replacing libraries

### PR DESCRIPTION
**Pull request by boooby19**
**Description**:
This PR modifies standardization for code which means we are trying to use just one library for annotations @NonNull and @Nullable - edu.umd.cs.findbugs.annotations
For this standardization it was neccessary to remove @NotNull annotations in the code.

**Related issue(s)**: #15375 

Fixes #

**Notes for reviewer**:
is it possible to do something similar like this? Thanks ! :) @netopyr

### CODE REVIEW

**Review by netopyr — DISMISSED** [review]
LGTM - thanks @boooby19!

**Comment by netopyr** [comment]
Hi @boooby19! Do you have questions regarding the DCO sign-off? Our [maintainer's guide](https://github.com/hashgraph/hedera-services/blob/develop/docs/maintainers-guide.md#dco-sign-off) provides a brief introduction. If you have further questions, please do not hesitate to ask.

**Comment by boooby19** [comment]
hello @netopyr , is it now okay? I just tried to add that sign off

**Comment by boooby19** [comment]
I am going to make a new fork and PR.

**Comment by boooby19** [comment]
i just marked the PR https://github.com/hashgraph/hedera-services/pull/16641

**Pull request closed without merging**
