### PR TITLE
chore: remove unused `hedera-evm-*` and `cli-clients` modules

### LINKED ISSUE #15253: Extract any in-use utility classes from `hedera-evm*` modules
### Problem

Mirror node will never need another version of the `hedera-evm` modules published, so we can remove them.

But there are a handful of utility classes we need to keep.

### Solution

Move these utility classes into `hapi-utils`.

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Description**:
 - Closes #15253 
 - Moves the three in-use classes from `hedera-evm` module (`EthSigsUtils`, `ValidationUtils`, and `InvalidTransactionException`) to `hapi-utils` for now.
 - Removes the otherwise unused `hedera-evm-*` and `cli-clients` modules (the latter was focused on dumping mono-service states, may be restored at some point for mod-service states as time permits).

### CODE REVIEW

**Review by david-bakin-sl — COMMENTED** [review]
The stuff in `com.hedera.services.cli.sign` is _not_ part of the state dumpers.  Not sure who created it or if it is still wanted.

SIgh.  Dumpers will be gone but not forgotten.  I'll have to get them back some time in the future.

**Review by jjohannes — APPROVED** [review]

**Review by jjohannes — CHANGES_REQUESTED** [review]
Thank you for this cleanup work!

Please also remove the following lines from `settings.gradle.kts`:

```
        module("cli-clients") { artifact = "services-cli" }

        module("hedera-addressbook-service") { artifact = "app-service-addressbook" }
        module("hedera-addressbook-service-impl") { artifact = "app-service-addressbook-impl" }
```

**Comment by tinker-michaelj** [comment]
> Thank you for this cleanup work!
> 
> Please also remove the following lines from `settings.gradle.kts`:
> 
> ```
>         module("cli-clients") { artifact = "services-cli" }
> 
>         module("hedera-addressbook-service") { artifact = "app-service-addressbook" }
>         module("hedera-addressbook-service-impl") { artifact = "app-service-addressbook-impl" }
> ```

Done, ty @jjohannes !

**Comment by jjohannes** [comment]
Sorry I meant to write to remove the two lines for "evm" not "addressbook".

**Comment by tinker-michaelj** [comment]
> Sorry I meant to write to remove the two lines for "evm" not "addressbook".
> 
> > // EVM has its own group
> > module("hedera-evm") { group = "com.hedera.evm"}
> > module("hedera-evm-impl") { group = "com.hedera.evm"}

Ah ofc, fixed this @jjohannes

**Review by jjohannes — DISMISSED** [review]

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM! Thanks @tinker-michaelj

**Review by david-bakin-sl — DISMISSED** [review]
LGTM (goodbye, dumpers, for now, it was nice to work on you)

**Review by kimbor — DISMISSED** [review]

**Review by Neeharika-Sompalli — APPROVED** [review]

**Review by kimbor — APPROVED** [review]

**Review by david-bakin-sl — APPROVED** [review]
LGTM

**Review by rbarkerSL — APPROVED** [review]
LGTM

**Pull request merged**
