### PR TITLE
test: add security v2 model tests for token associate

### PR DESCRIPTION
**Pull request by anastasiya-kovaliova**
**Description**:

Add suggested test from 11241
SIGNER → call → CONTRACT → call → HTS
SIGNER → call →CONTRACT A→ call →CONTRACT B → call → PRECOMPILE(HTS)

[V2_SECURITY-006] - [Non Nested] TokenAssociate Fungible and NFTs - positive tests
[V2_SECURITY-031] - [ContractKey] Token with a DelegateContractKey can execute associate from a CALL - negative tests for both Fungible and NFTs
[V2_SECURITY-010] - [Nested] Associate of NFTs and Fungible tokens - negative tests

Test Plan: https://www.notion.so/limechain/V2-Security-Model-Test-Plan-Specification-98472925ed534c6d91950273975bd74c?pvs=4

-->

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by mhess-swl — COMMENTED** [review]
This looks fine to me, but since it's completely contract related, others should review as well

**Comment by mhess-swl** [comment]
> These failing `_Eth` suites are created in CI by trying to switch all ContractCall's to EthereumTransaction's. Fix for these is needed

To clarify, do we need a fix from your team or do we need a fix from the services team?

**Review by tinker-michaelj — APPROVED** [review]
LGTM, ty @anastasiya-kovaliova !

**Review by tinker-michaelj — APPROVED** [review]
LGTM, ty @anastasiya-kovaliova !

**Review by mhess-swl — APPROVED** [review]

**Pull request merged**
