### PR TITLE
test: Added a test to submit DAB transactions for JRS test

### PR DESCRIPTION
**Pull request by Neeharika-Sompalli**
Fixes https://github.com/hashgraph/hedera-services/issues/15488

- Added a test to submit DAB transactions for JRS test
- Added node transactions in `throttles.json`

### CODE REVIEW

**Review by tinker-michaelj — DISMISSED** [review]
LGMT, tyvm @Neeharika-Sompalli !

**Review by Nana-EC — APPROVED** [review]

**Review by iwsimon — DISMISSED** [review]
LGTM, thanks @Neeharika-Sompalli

**Review by tinker-michaelj — APPROVED** [review]
LGTM, tyvm @Neeharika-Sompalli !

**Review by Nana-EC — APPROVED** [review]
LG

**Pull request merged**
