### PR TITLE
fix: waive privileged signing requirements for file append

### LINKED ISSUE #13475: `FileAppendHandler#preHandle()` should waive privileged signing requirements
### Description

The fee schedules admin (`0.0.56`) should not be required to sign with the `0.0.111` admin key doing a `FILE_APPEND`.

### Steps to reproduce

1. Set the `0.0.56` key to a different key from `0.0.111`
2. Attempt a fee schedules update e.g. with `gcr.io/hedera-registry/yahcli:0.4.2`; the `FileAppend`'s will fail with `INVALID_SIGNATURE`.

### Additional context

_No response_

### Hedera network

mainnet

### Version

v0.49.7

### Operating system

None

### PR DESCRIPTION
**Pull request by povolev15**
Waive privileged signing requirements for file append

**Related issue(s)**:

Fixes #13475

### CODE REVIEW

**Review by thomas-swirlds-labs — DISMISSED** [review]
LGTM. Thanks! @tinker-michaelj 💯

**Review by tinker-michaelj — CHANGES_REQUESTED** [review]
Oops this doesn't actually work, will ping out-of-band; we need a `FILE_APPEND`-specific version of [this method](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileSignatureWaiversImpl.java#L49).

**Comment by povolev15** [comment]
> Oops this doesn't actually work, will ping out-of-band; we need a `FILE_APPEND`-specific version of [this method](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileSignatureWaiversImpl.java#L49).

fixed it thank for the catch

**Review by tinker-michaelj — APPROVED** [review]
LGTM, ty @povolev15 !

**Pull request merged**
