### PR TITLE
chore: Fix state dumpers

### LINKED ISSUE #12232: Validate state using differential testing with state dumpers
Pick a round for differential testing and use state dumpers to validate the end state for following maps

- [x] #12332
- [x] #12333
- [x] #12334

### PR DESCRIPTION
**Pull request by Neeharika-Sompalli**
Related to #12232 
Fixes #https://github.com/hashgraph/hedera-services/issues/12332

- Moved all mono-service related dumping code and utilities to mono-service.
- This is needed to dump needed contents from state during mono-service replay to compare state with mod service replay

### CODE REVIEW

**Review by jeromy-cannon — DISMISSED** [review]

**Review by iwsimon — APPROVED** [review]
LGTM. Thanks @Neeharika-Sompalli !

**Review by jeromy-cannon — DISMISSED** [review]

**Review by iwsimon — DISMISSED** [review]
LGTM. Thanks @Neeharika-Sompalli

**Review by jeromy-cannon — DISMISSED** [review]

**Review by tinker-michaelj — DISMISSED** [review]
LGTM, tyvm @Neeharika-Sompalli !

**Review by iwsimon — APPROVED** [review]

**Review by tinker-michaelj — APPROVED** [review]
LGTM, tyvm @Neeharika-Sompalli !

**Pull request merged**
