### PR TITLE
CI-enabled 2069

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Summary of changes**

Beyond #2069, does the following code cleanup:
- Removes duplication in custom fee code (eliminate non-GRPC, non-`FastCopyable` type hierarchy).
- Moves fee validation logic into the `FcCustomFee` types to better isolate this responsibility.
- Uses a `Creation` process object to reduce complexity of `TokenCreateTransitionLogic`.
- Along with the simplifications above, makes both `TokenCreateTransitionLogicTest` and `TokenFeeScheduleUpdateTransitionLogic` use the `MockitoExtension`.

### CODE REVIEW

**Review by Daniel-K-Ivanov — APPROVED** [review]
Great work!

**Review by qnswirlds — APPROVED** [review]
Looks great! Thanks!

**Review by joan41868 — APPROVED** [review]
Looks great!

**Review by ljianghedera — APPROVED** [review]
Nice work!

**Pull request merged**
