### PR TITLE
feat: Disable token associations in AccountInfo, ContractInfo, and AccountBalance

### LINKED ISSUE #12291: Deprecate token associations in account info queries
Disable the feature flag `balancesInQueries.enabled`. This will stop listening token associations in responses to `ContractGetInfo`, `AccountGetInfo`, and `GetAccountBalance` queries.

### PR DESCRIPTION
**Pull request by netopyr**
This PR disables the listing of token associations in `AccountInfo`, `ContractInfo`, and `AccountBalance` as defined in [HIP-367](https://hips.hedera.com/hip/hip-367)

Fixes #12291

### CODE REVIEW

**Review by tinker-michaelj — APPROVED** [review]
LGTM, ty @netopyr !

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM! Thanks @netopyr

**Comment by tomachianura** [comment]
is that a joke?
we've been discussing many times about the importance of having AccountBalance enabled.
there's a lot of use case where this feature is mandatory and needed for those applications buildining and working on native services.
You just can't remove it as if it's nothing, this is going to create a major issue in the entire Hsuite Engine, and in every single appnet working on the native layer.
We can't rely on the mirror nodes to fetch real time balances, it's just wrong from an architectural perspective, highly unefficient and mostly unsecure.

Last time we had a long discussion about it, and we all agreed in **not removing AccountBalance never ever**, MUST BE BROUGHT BACK.

**Comment by tomachianura** [comment]
CleanShot 2024-06-06 at 10 02 12@2x

**Comment by tomachianura** [comment]
@sergmetelin you promised that to the community, please stand by your words.

**Comment by tomachianura** [comment]
CleanShot 2024-06-06 at 10 04 38@2x

**Pull request merged**
