### PR TITLE
chore: Add github actions for uploading junit test reports as artifacts

### LINKED ISSUE #12295: Upload junit test reports as artifacts
Currently junit reports from test are generated and processed as part of the CI pipelines, but the files themselves are not available. 

To better support the optimization of tests runtime they need to be available as an artifact on job runs.

### PR DESCRIPTION
**Pull request by yaroslav-007**
**Description**:
Add github actions for uploading the junit test reports as artifacts.

Fixes #12295

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by nathanklick — CHANGES_REQUESTED** [review]
These should not be uploaded due to size concerns.

**Comment by nathanklick** [comment]
@yaroslav-007 We should limit these to only uploading the artifacts when the associate test step fails.

**Comment by isavov** [comment]
@nathanklick  This PR is in support of #12269 with the goal of allowing QA engineers to analyze in detail the time each test consumes. In that sense it would be more useful for them to have the junit reports for both successful and failed runs. Currently we upload the full network logs as well, which are often bigger than the reports.
To facilitate the intent of the original issue I would suggest we could do either or all of the following:
1. Always upload test reports artifacts, but limit retention time using the `retention-days` config in the action to a short time (5-7 days)
2. Upload the network node logs only on failed tests
What do you think?

**Comment by yaroslav-007** [comment]
Hello @nathanklick,

I have change the upload action to be trigger when there is failure and artifacts to be kept for 7 days.

**Review by isavov — APPROVED** [review]

**Review by nathanklick — APPROVED** [review]

**Pull request merged**
