### PR TITLE
fix: fix javadoc errors

### LINKED ISSUE #13219: Fix javadoc errors
Problem:
Javadoc generation errors out with a number of javadoc compile errors.

Solution:
Fix the errors.

### PR DESCRIPTION
**Pull request by kimbor**
**Description**:
Fix a number of errors that occur when generating javadoc due to improperly formatted javadoc tags.

**Related issue(s)**:

Fixes #13219

### CODE REVIEW

**Comment by kimbor** [comment]
This PR is nearly entirely duplicated in PR #11731.

**Review by povolev15 — APPROVED** [review]
LGTM TY @kimbor

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM! Thanks @kimbor

**Review by david-bakin-sl — APPROVED** [review]
LGTM TY!

**Review by lukelee-sl — APPROVED** [review]
LGTM.  For smart contracts only.  Thank you!

**Pull request merged**
