### PR TITLE
Migrate EVM to 22.10.x

### LINKED ISSUE #4119: Upgrade Hyperledger Besu EVM to 22.10.x
Upgrade the Hyperledger Besu EVM to 22.10.x

Loop unrolling has shown performance improvements of 20%-100% depending on use case.

### PR DESCRIPTION
**Pull request by shemnon**
**Description**:
Migrate the Hyperledger Besu EVM to the 22.10.x version.

Between 20%-100% speed improvement is expected depending on the contract.

**Related issue(s)**:

Fixes #4119 

**Notes for reviewer**:

This is RC-2 code.  We should wait until RCS releases before merging

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by Nana-EC — APPROVED** [review]
LG.
Majority of the changes are going from `OptionalLong` -> `Long`. 
Would be good to note this and any other high level changes that are contributing to the perf changes.
Or may just not the release notes of the new besu client version

**Comment by Nana-EC** [comment]
@shemnon should this run the `CI:FinalTests` and `CI:FullStackTests` also?

**Comment by shemnon** [comment]
Performance gains come from https://github.com/hyperledger/besu/pull/4540 and https://github.com/hyperledger/besu/pull/4533.  OptionalLong changes are part of 4533, and 4540 caused the changes to the tracer interfaces.

**Review by tinker-michaelj — APPROVED** [review]
LGTM!

**Review by qnswirlds — APPROVED** [review]

**Pull request merged**
