### PR TITLE
fix: make pureChecks required in all handlers (#12578)

### LINKED ISSUE #12619: make pureChecks required in all handlers
### Problem

TransactionHandler has a default empty implementation of pureChecks, which means that all inheriting classes could optionally implement pureChecks or accept the empty default. When this default was created, the plan was to create pureChecks implementations for all handler classes and then to remove the default.

### Solution

Remove the default empty TransactionHandler.pureChecks() implementation and add overrides for all implementing classes which previously lacked one.

### Alternatives

_No response_

### LINKED ISSUE #12644: Validate pureChecks in smart contracts service
The integration tests of the SDK found two cases where invalid transactions led to unexpected Exceptions. We should make sure that each handler has a `pureChecks()` method (even if it is empty initially) and review the pure checks for all handlers of the smart contracts service.

### PR DESCRIPTION
**Pull request by kimbor**
**Description**:
Cherry pick of PR #12578 to develop

Fixes #12619 
Fixes #12644

### CODE REVIEW

**Review by povolev15 — APPROVED** [review]
LGTM thank you @kimbor

**Review by jeromy-cannon — APPROVED** [review]

**Review by iwsimon — APPROVED** [review]
LGTM. Thanks @kimbor

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM !

**Review by tinker-michaelj — APPROVED** [review]
LGTM, ty @kimbor !

**Pull request merged**
