### PR TITLE
Removing unused assignments, imports and methods to fix SonarCloud issues

### LINKED ISSUE #2059: Remove unused assignments and methods from Major Sonar issues
### Problem

There are unused local variable assignments and methods that should be removed.

https://sonarcloud.io/project/issues?id=com.hedera.hashgraph%3Ahedera-services&resolved=false#

### Solution

Fixing the bugs reported in SonarCloud.

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by abhishek-hedera**
Signed-off-by: abhishek-hedera <abhishek.pandey@hedera.com>

**Description**:
Removed unused imports, methods and variables, renamed some variables to resolve SonarCloud major issues, added tests for `CommonUtils` and `RequestBuilder`

**Related issue(s)**:

Fixes #2059

### CODE REVIEW

**Review by qnswirlds — APPROVED** [review]
The changes in general look good. But as a practice of refactoring, we want to do once and for all, so we don't have to go back fixing them later. Here are some suggestions:

- Add tests (if missing) where changes are made
- Add `final` keyword where appropriate
- Completely remove (or combine) unnecessary lines
- Check SonarCloud for the feature branch to make sure of 100% test coverage of new code (strongly recommended) and no new Sonar issues (can be considered as a requirement for merging)
Your branch is having a 60% new code coverage
https://sonarcloud.io/dashboard?branch=02059-M-RemoveUnusedAssignments&id=com.hedera.hashgraph%3Ahedera-services

I actually had some of the common touched code (not merged yet) with yours, so please take a look
https://github.com/hashgraph/hedera-services/commit/7724bf3f217c7f108a8a760cc28457eace95e918

I would also recommend we fix SonarCloud issues in groups. Do not just pick a few issues of different types and fix. It is very hard to control and share the work that way.

**Review by anighanta — APPROVED** [review]

**Review by anighanta — APPROVED** [review]
PLease resolve merge conflicts with `master`

**Comment by abhishek-hedera** [comment]
> Please resolve merge conflicts with `master`

Resolved, thanks!

**Review by qnswirlds — APPROVED** [review]
LGTM

**Review by anighanta — APPROVED** [review]

**Pull request merged**
