### PR TITLE
01497 d enable sonar check for pr

### LINKED ISSUE #1497: Add SonarCloud to CI steps
**Summary**
In order to main clean codebase, SonarCloud needs to be added as a step to the Continuous-Integration steps in services. 
If possible it will be better to be executed only when a PR is opened, instead of running on every commit.

### PR DESCRIPTION
**Pull request by ljianghedera**
**Related issue(s)**:
Closes #1497

Successful running of CircleCi build with Sonar scan report enabled: https://app.circleci.com/pipelines/github/hashgraph/hedera-services/16768/workflows/39ee0f87-ad92-46a3-888a-6ca453a3d4fb

An example of Sonar scan failure slack report: https://hedera-hashgraph.slack.com/archives/CMD3V6ZC4/p1623441562146800

**Summary of the change**:
1. Option 1 to enable sonar check in CircleCi build for PR merge requests. In this approach, the Sonar scan is not added into github project's check, like codecov. Instead, it is added as CircleCi's job and steps. If the Sonar scan doesn't find any issue, it will do nothing. If there is issue in sonar scan, a slack report will be sent to `hedera-cicd` channel and you can navigate to sonarcloud UI report for more details; 

We'll stay with this implementation for couple of weeks. If it turns out that this is not satisfactory, we can move to option 2 which is to embed the Sonar scan in github project's `checks` (just like codecov). 

**External impacts**:
None.

**Applicable documentation**
- [ ] Javadoc
- [ ] HAPI protobuf comments
- [ ] README

### CODE REVIEW

**Review by qnswirlds — APPROVED** [review]
Overall LGTM. But I think we should notify via Slack when the SonarCloud quality gate passed as well.

**Review by tinker-michaelj — APPROVED** [review]
LGTM!

**Review by abhishek-hedera — APPROVED** [review]
LGTM

**Review by Neeharika-Sompalli — APPROVED** [review]

**Comment by ljianghedera** [comment]
@qnswirlds Added code to send successful sonar scan to slack. Here is the URL for the CircleCi job: https://app.circleci.com/pipelines/github/hashgraph/hedera-services/16860/workflows/40ffe8b3-ff81-4ebb-a657-5dbe2710a454/jobs/70717

which has the following message in its   `Check SonarCloud Quality Gate` step : 
```
------------------------------------------------------------------------------------------------------------------------------------------------------
	SONAR QUALITY GATE:	PASSED
	Dashboard URL:		https://sonarcloud.io/dashboard?branch=01497-D-enable-sonar-check-for-PR&id=com.hedera.hashgraph%3Ahedera-services
------------------------------------------------------------------------------------------------------------------------------------------------------
CircleCI received exit code 0
```

if for some rare case, develop want to look into the sonarcloud analysis report, which normally doesn't have meaningful information. 

Hence the successful slack report link: https://hedera-hashgraph.slack.com/archives/CMD3V6ZC4/p1623689912157900 seems not necessary.

**Comment by qnswirlds** [comment]
I don't disagree. But my concern is different. When we create many branches in the CI workflow, the end-point of each branch must notify us so we know that branch is finished or we still have to wait for it. Another solution for this is have a single end-point of `notifyViaSlack` for all branches in the CI workflow.

**Comment by ljianghedera** [comment]
@Quan I am not sure if I follow what you mean here. Let's have a chat when we have a chance.

**Pull request merged**
