### PR TITLE
chore: removing notnull annotations and replacing libraries

### PR DESCRIPTION
**Pull request by boooby19**
Description:
This PR modifies standardization for code which means we are trying to use just one library for annotations @nonnull and https://github.com/nullable - edu.umd.cs.findbugs.annotations
For this standardization it was neccessary to remove https://github.com/NotNull annotations in the code.

Related issue(s): https://github.com/hashgraph/hedera-services/issues/15375

Fixes #

Notes for reviewer:
@netopyr hope that third chance would be good

### CODE REVIEW

**Review by netopyr — APPROVED** [review]
LGTM - thanks @boooby19

**Review by reachtobhavesh — APPROVED** [review]
Looks good to me.

**Comment by netopyr** [comment]
@boooby19 Thanks a lot! Unfortunately, there still seems to be an issue. According to GitHub, you did not sign the commits. Can you please check this?

**Comment by boooby19** [comment]
hello @netopyr sorry but i dont understand what is a problem now? can you give a little explain? because i see that "DCO" mark passed, thanks !

**Comment by netopyr** [comment]
All commits to our repository have to be GPG-signed, which proves it was really you. Instructions are in [CONTRIBUTING.md](https://github.com/hashgraph/.github/blob/main/CONTRIBUTING.md). If you have any more questions, please post them here. I am not a GitHub expert, but I will find somebody to help.

**Pull request closed without merging**
