### PR TITLE
00553-D-ContractMemoSizeNotEnforced

### LINKED ISSUE #553: Contract memo size limit not enforced
Created by [185](https://github.com/swirlds/hedera-fpcomplete-audit/pull/185)

## Situation

Both the [ContractCreate](https://docs.hedera.com/guides/docs/hedera-api/smart-contracts/contractcreate) and the [ContractUpdate](https://docs.hedera.com/guides/docs/hedera-api/smart-contracts/contractupdate) operations include a `memo` field with a note.

> max 100 bytes
When the node receives a transaction from a client via the gRPC interface, this constraint appears to be enforced as a part of validations in the `TransactionHandler.validateTransactionPreConsensus` method with this concrete check at https://github.com/swirlds/services-hedera/blob/4dca8c55e200e70774f2906f44a1bbbd69944ef3/hedera-node/src/main/java/com/opencrowd/handler/TransactionHandler.java#L431

No corresponding checks were found for transactions when they come from other nodes and receive consensus (with service logic invoked as a part of `AwareProcessLogic.incorporateConsensusTxn`).

## Problem

This issue is not a problem as long all nodes can be trusted, but if we understand correctly, that will not be the case anymore in the future.

### PR DESCRIPTION
**Pull request by cesaragv**
**Related issue(s)**:
Closes #553 

Related to [185](https://github.com/swirlds/hedera-fpcomplete-audit/pull/185)

**Summary of the change**:
Validates Contract memo size in AwareProcessLogic.incorporateConsensusTxn`

### CODE REVIEW

**Review by tinker-michaelj — CHANGES_REQUESTED** [review]
As written, this would prevent any `ContractCreate`/`ContractUpdate` with an oversized memo from being handled; so no fees would be charged, no `TransactionRecord` would be streamed or made queryable, etc.

This is inconsistent with how all other invalid transactions are treated upon reaching consensus.

Imo it is strongly preferable to check the memo size in `AwareProcessLogic#handleTransaction`, which contains the hooks into the legacy Smart Contract handling methods. 

If the check fails, handling should proceed analogously to [line #367](https://github.com/hashgraph/hedera-services/blob/master/hedera-node/src/main/java/com/hedera/services/legacy/services/state/AwareProcessLogic.java#L367), a failure scenario in which the bytecode file is missing:
```
...
		if (txn.hasContractCreateInstance()) {
			FileID fid = txn.getContractCreateInstance().getFileID();
			try {
				if (!ctx.hfs().exists(fid)) {
					record = ctx.contracts().getFailureTransactionRecord(txn, consensusTime, INVALID_FILE_ID);
```

**Comment by cesaragv** [comment]
> AwareProcessLogic

@tinker-michaelj There is no  `AwareProcessLogic#handleTransaction`, do you mean `AwareProcessLogic#doProcess`?

**Comment by tinker-michaelj** [comment]
> > AwareProcessLogic
> 
> @tinker-michaelj There is no `AwareProcessLogic#handleTransaction`, do you mean `AwareProcessLogic#doProcess`?

Oh sorry, it's [`processTransaction` here](https://github.com/hashgraph/hedera-services/blob/master/hedera-node/src/main/java/com/hedera/services/legacy/services/state/AwareProcessLogic.java#L361). 🤦

**Review by tinker-michaelj — APPROVED** [review]
LGTM

**Pull request merged**
