### PR TITLE
Apply gradle spotless on all files

### PR DESCRIPTION
**Pull request by Neeharika-Sompalli**
Signed-off-by: Neeharika-Sompalli <neeharika.sompalli@hedera.com>

Apply gradle spotless on all files to avoid confusing changes on future PRs.
**NO CODE CHANGES**

### CODE REVIEW

**Review by tinker-michaelj — DISMISSED** [review]
Let's go for it 😅

**Review by nathanklick — CHANGES_REQUESTED** [review]
Changing the license header has caused spotlessApply to reformat every file in the repository including files which were already properly formatted. This is not an acceptable way to reformat the remaining files. Instead temporarily commenting out `ratchetFrom("origin/master")` should be used to reformat files which have not been modified it a branch.

**Review by nathanklick — APPROVED** [review]

**Comment by rbair23** [comment]
@Neeharika-Sompalli's stats are gonna go through the roof this week 😄 😄

**Review by tinker-michaelj — APPROVED** [review]
Ty Neeha, LGTM!

**Review by nathanklick — APPROVED** [review]

**Pull request merged**
