### PR TITLE
feat(pbj): upgrade PBJ dependency to v0.8.5 to default repeated field…

### PR DESCRIPTION
**Pull request by anthony-swirldslabs**
…s to empty lists

**Description**:
Upgrading PBJ to v0.8.5. Previous versions of PBJ already defaulted repeated fields in models to empty lists in their parsers and Builders. With v0.8.5, model constructors also do the same, and this allows PBJ to mark all repeated fields as `@NonNull`.

**Related issue(s)**:

Fixes https://github.com/hashgraph/pbj/issues/238

**Notes for reviewer**:
* v0.8.5 is released: https://central.sonatype.com/artifact/com.hedera.pbj/pbj-runtime/versions
* The PBJ PR with the actual fix: https://github.com/hashgraph/pbj/pull/239

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by jeromy-cannon — DISMISSED** [review]

**Review by lukelee-sl — DISMISSED** [review]
Makes sense to me.  Only commenting for the smart contracts changes.

**Review by kimbor — APPROVED** [review]

**Review by Neeharika-Sompalli — DISMISSED** [review]
LGTM from `hedera-base` changes . Thanks @anthony-swirldslabs

**Review by lukelee-sl — DISMISSED** [review]
LGTM

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM !

**Review by lukelee-sl — APPROVED** [review]
LGTM

**Review by nathanklick — APPROVED** [review]

**Pull request merged**
