### PR TITLE
chore: Cleanup and extract fee functionality from contexts

### LINKED ISSUE #13910: Extract fee calculation

### PR DESCRIPTION
**Pull request by netopyr**
**Description**:

This PR cleans up the fee functionality and extracts its code from `HandleContext` and `FeeContext`

It also includes some minor fixes that the IDE showed for some tests.

**Related issue(s)**:

Fixes #13910 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by tinker-michaelj — DISMISSED** [review]
LGTM, ty @netopyr !

**Review by Neeharika-Sompalli — DISMISSED** [review]
LGTM! Thanks @netopyr . But seems like there are merge conflicts

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM! Thanks @netopyr

**Review by lukelee-sl — APPROVED** [review]
All the smart contract module changes LGTM.

**Pull request merged**
