### PR TITLE
feat: Add gasPerConsSec metric

### PR DESCRIPTION
**Pull request by netopyr**
This PR add the `gasPerConsSec` metric to modular code.

### CODE REVIEW

**Review by thomas-swirlds-labs — APPROVED** [review]
LGTM!

**Review by povolev15 — APPROVED** [review]
LGTM

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM ! Thanks @netopyr

**Review by kimbor — APPROVED** [review]

**Review by tinker-michaelj — APPROVED** [review]
Looks right to me, ty @netopyr !

**Pull request merged**
