### PR TITLE
Consolidate junit v5 tests

### LINKED ISSUE #1003: Remove @RunWith(JUnitPlatform.class) from all tests
Related to #907, this is a way to run junit v5 tests within a junit v4 environment, which is not needed because we have the junit v5 environment set up. Remove those to simplify the tests and to avoid confusion.

### PR DESCRIPTION
**Pull request by qnswirlds**
**Related issue(s)**:
Closes #1003

**Summary of the change**:
Remove @RunWith(JUnitPlatform.class) from all tests

**External impacts**:
None.

**Applicable documentation**
None.

### CODE REVIEW

**Review by tinker-michaelj — APPROVED** [review]
Makes sense!

**Comment by ljianghedera** [comment]
The changes are fine. Just a quick question, after removing the @Runwith(JUnitPlatform.class), are we still able to run individual test in Intellij or from command line?

**Comment by qnswirlds** [comment]
> The changes are fine. Just a quick question, after removing the @RunWith(JUnitPlatform.class), are we still able to run individual test in Intellij or from command line?

@ljianghedera, yes, we are still able to.

**Comment by ljianghedera** [comment]
Nice. Thanks for the confirmation.

**Pull request merged**
