### PR TITLE
chore: Cherry-pick: Increase max token associations to 50M

### LINKED ISSUE #12094: Move configuration from application.properties to code
The `application.properties` file used in MainNet contained a number of configurations. These need to become the new defaults (if they are not already), and the `application.properties` file has to be cleared.

### LINKED ISSUE #12218: Increase max. number of token associations
Increase the maximum number of token associations to 50 million.

### PR DESCRIPTION
**Pull request by netopyr**
Cherry pick of #12282

Closes #12218 
Closes #12094

### CODE REVIEW

**Review by SimiHunjan — APPROVED** [review]

**Review by povolev15 — APPROVED** [review]
LGTM

**Review by thomas-swirlds-labs — APPROVED** [review]
LGTM. Thanks @netopyr !

**Review by Nana-EC — APPROVED** [review]

**Review by poulok — APPROVED** [review]

**Review by cody-littley — APPROVED** [review]
Approving for the hashgraph team since I was asked. Note that hashgraph team doesn't own any files changed in this branch, so probably best to seek other reviewers as well. 😅

**Review by tinker-michaelj — APPROVED** [review]
LGTM, ty @netopyr !

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM!

**Pull request merged**
