### PR TITLE
fix: 11042 Upgraded PBJ version to 0.7.12

### LINKED ISSUE #11042: fix: Update PBJ version to fix issue in the generated code
### Problem

There is an issue with a missing import for `Bytes` class - see https://github.com/hashgraph/pbj/issues/174

It's already fixed in PBJ 0.7.12

### Solution

Update PBJ dependencies in `hedera-services`

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by imalygin**
This PR upgrades PBJ version to 0.7.12

**Related issue(s)**:

Fixes #11042 
Relates to https://github.com/hashgraph/pbj/issues/174

### CODE REVIEW

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM ! Thanks @imalygin

**Review by Neeharika-Sompalli — COMMENTED** [review]
There are some compile errors on this. If we change the `hapiProtoBranchOrTag=add-pbj-types-for-state` we can validate it fixes the issue also.

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM !

**Review by Neeharika-Sompalli — APPROVED** [review]

**Review by thomas-swirlds-labs — APPROVED** [review]
LGTM. Thanks @imalygin 👍

**Review by tinker-michaelj — APPROVED** [review]
LGTM, thanks @imalygin

**Pull request merged**
