### PR TITLE
Spotless code style

### PR DESCRIPTION
**Pull request by shemnon**
**Description**:

Add Spotless Code Style Checking to the codebase.

This PR adds the `pom.xml` configuration to run spotless with the Google Java Format as the style.
All of the source files were then reformatted with `./mvnw spotless:apply`

**Notes for reviewer**:

The commit with the pom.xml changes are the only non-mechanical changes.  The other commit is mechanically generated.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Comment by steven-sheehy** [comment]
This is quite the change to the style. We should have consistent code style across projects. Is leadership recommending we switch to Google Code style? If so, we should have that in the engineering handbook and it should be communicated. I'm not a fan of 2 spaces for indentation, but consistency is important.

Can this formatting be automated via commit hook or at least verified in CI so that it continues to stay consistent?

**Comment by shemnon** [comment]
It was discussed in the hedera-services standup, and the team was generally supportive.  This is a "red herring" to get a scope of the impact as well as feedback.

The plugin I am doing enforces it at compile time, breaking the build in the `verify` step if formatting is not correct.  So CI will enforce this standard as a part of a successful build.

There are other maven plugins that will re-format as a git commit. My preference is to make it a part of the build to keep it consistant at all stages.  Devs can run `./mvnw spotless:apply` to re-format their code in place. There are also IntelliJ and eclipse plugins that will apply the formatting as well with a standard keystroke (command+L for mac intellij, for example).

**Review by tinker-michaelj — APPROVED** [review]
LGTM

**Review by qnswirlds — APPROVED** [review]
Overall LGTM. A few comments:
- Needs to refresh with `master` and resolve conflicts
- Does spotless support Oracle java code style? Adopting Oracle code style will be a less painful change.

**Comment by shemnon** [comment]
Which oracle style?  The older one doesn't have anything to say about lambdas. The hotspot style has many statements that make mechanical enforcement difficult. If there was an Eclipse format xml or IntelliJ style this plugin can support it.  But one of the features I like best about Google's style is there are no knobs to turn.  It's a bit like `gofmt` in that regard.

**Comment by rbair23** [comment]
@steven-sheehy I agree that we must have the same style across all our projects. I prefer a style that we can all agree to over one that agrees with my personal tastes, as long as it works. I haven’t used two space indentation in probably 15 years, but I can live with it. At least we can all agree it is SPACES and not TABS :-).

**Comment by rbair23** [comment]
I really don’t want to open Pandora’s box, but… https://github.com/google/google-java-format/issues/525

**Comment by rbair23** [comment]
Now that I opened the box, I think we should either take Google style as is or AOSP Google style. The less choice, the easier the pill will be to swallow :-)

**Comment by steven-sheehy** [comment]
Looking at AOSP, it has a lot of things specific to Android and C/C++. See its [field naming conventions](https://source.android.com/setup/contribute/code-style#follow-field-naming-conventions) that require certain fields start with `s` or `m`. Definitely think we shouldn't use AOSP.

While Google Java Format doesn't want you to, it does look like the spotless plugin lets you at least [tweak](https://github.com/google/google-java-format/issues/525#issuecomment-729503265) things like indentation. I think since devs are familiar with working with 4 spaces and to minimize formatting changes, we could at least adjust that.

**Comment by rbair23** [comment]
I also saw a lot of people saying not to use AOSP. Let’s stick with the Google style then. I’m ok with 4 spaces or 2 spaces whatever we decide.

**Comment by tinker-michaelj** [comment]
Done!

**Pull request closed without merging**
