### PR TITLE
feat: Enhance storage (file) store dumper to handle modular representation

### PR DESCRIPTION
**Pull request by vtronkov**
**Description**:
* Adding modular store dumper for the files

**Related issue(s)**:

Fixes https://github.com/hashgraph/hedera-services/issues/10920

### CODE REVIEW

**Review by petreze — APPROVED** [review]

**Comment by david-bakin-sl** [comment]
Hmm.  The dumps from the mono code here definitely won't match the dumps from the modular code here because in the mono code file contents and file metadata are in two separate tree nodes and are merged for the dump while in modular the contents + metadata are in one tree node and no merge needed.

We already _have_ a mono dumper that works - as a separate tool.  We have to think about whether the flow we're looking for requires the mono dumper to be _here_ in the node (it might very well) or if we can run the separate cli tool that exists.

Either the _full_ mono code needs to be here - see `DumpFilesSubcommand.collectFiles` where first it gets files + metadata nodes into separate hashmaps (L435-473) and then does the merge (L480-490) - _or_ I'd prefer that mono code just write a one line file saying "this is invalid, you need to run the cli tool!".

Let's discuss this in (internal) Slack.  I'll start the conversation there, then we can update the issue.

(I'll review the new modular code shortly.)

**Review by david-bakin-sl — CHANGES_REQUESTED** [review]
Modular traversal looks fine.  Mono traversal needs work - see previous comment please!

**Review by david-bakin-sl — APPROVED** [review]
TY for that mono traversal fixup.  LGTM

**Review by tinker-michaelj — APPROVED** [review]
This looks great to me, ty @vtronkov !

**Pull request merged**
