### PR TITLE
feat: Add TokenUpdateNFTs as a smart contract operation v2

### LINKED ISSUE #14589: Define and implement HTS function call TokenUpdateNfts

### PR DESCRIPTION
**Pull request by stoyanov-st**
**Description**:
**_NOTE:_** This PR is copied from [PR](https://github.com/hashgraph/hedera-services/pull/14670)
Due to DCO issues we had to open this one with the exact changes and linked issues.

Original description from initial [PR](https://github.com/hashgraph/hedera-services/pull/14670)
- Add `TokenUpdateNFTs` as a smart contract operation - `updateNFTsMetadata(address, int64[], bytes)`
- Add numeric validation test for the serial numbers of the new smart contract operation.
- Create `UpdateTokenMetadataTest.java` and add success cases. Since we want to add new metadata-related operations soon, this test class can be used for them as well.
- Add unit tests for new classes.

**Related issue(s)**:

Fixes #14589 #14620 

**Notes for reviewer**:

**TODO**

- [ ] After confirmation of all the changes in this PR, I will open one in smart-contracts repo, to apply the changes to `IHederaTokenService.sol` and `HederaTokenService.sol`

### CODE REVIEW

**Review by lukelee-sl — APPROVED** [review]
LGTM

**Review by lukelee-sl — APPROVED** [review]
LGTM

**Review by Neeharika-Sompalli — DISMISSED** [review]
LGTM from hedera-base

**Review by lukelee-sl — COMMENTED** [review]
LGTM

**Review by lukelee-sl — APPROVED** [review]
LGTM

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM!

**Review by Nana-EC — APPROVED** [review]

**Pull request merged**
