### PR TITLE
fix: (cherry-pick) Use restart method to all token schemas 

### PR DESCRIPTION
**Pull request by Neeharika-Sompalli**
Fixes https://github.com/hashgraph/hedera-services/issues/13677
Cherry-pick https://github.com/hashgraph/hedera-services/pull/13673

### CODE REVIEW

**Review by thomas-swirlds-labs — DISMISSED** [review]
LGTM @Neeharika-Sompalli 🎉

**Review by iwsimon — DISMISSED** [review]
LGTM. Thanks @Neeharika-Sompalli

**Review by tinker-michaelj — APPROVED** [review]
LGTM, ty @Neeharika-Sompalli !

**Review by tinker-michaelj — APPROVED** [review]
LGTM, ty @Neeharika-Sompalli !

**Review by iwsimon — APPROVED** [review]
LGTM. Thanks @Neeharika-Sompalli

**Review by iwsimon — APPROVED** [review]
LGTM. Thanks @Neeharika-Sompalli

**Pull request merged**
