### PR TITLE
chore: 11772 Refactored `AddressBook` - it's no longer a `MerkleLeaf`

### LINKED ISSUE #11772: Refactor `AddressBook`
Currently, `AddressBook` is an instance of `MerkleLeaf`. However, it's a part of `PlatformState` and it no longer needs to be an instance of `MerkleLeaf` as it's not used as such. The only thing that it needs to be is `SelfSerializable` and `Hashable`.

### PR DESCRIPTION
**Pull request by imalygin**
**Description**:

This is a clean up. `AddressBook` objects are no longer used as `MerkleLeaf` objects, because `AddressBook` is now a part of `PlatformState` object which, in it's turn, is a  `MerkleLeaf`. 

So, `AddressBook` should no longer implement this interface. It only needs to be  `Iterable`, `SelfSerializable`, and Hashable.

**Related issue(s)**:

Fixes #11772

### CODE REVIEW

**Review by cody-littley — APPROVED** [review]

**Review by edward-swirldslabs — COMMENTED** [review]
A couple observations: 
1. the removal of the leaf index for `LEGACY_ADDRESS_BOOK` is happening in the mono repo.  If this change goes through, does something similar need to happen in the modular repo? 
2. How does this change interact with the Dynamic Address Book  (DAB) effort?   The existing `AddressBook` construct is becoming the `ConsensusRoster` and Hedera will move forward with their own definition of what an `AddressBook` means to them.   Would that new concept of a Hedera `AddressBook` live at this index that is being dropped?  

@iwsimon

**Comment by imalygin** [comment]
@edward-swirldslabs 

1. Correct me if I'm wrong, but, as far as I can tell, is not used as a part of the Merkle Tree. It is still there just because it was not removed, and this PR is removing it. There is another Merkle leaf - `PlatformState` - and `AddressBook` is a part of that. 
2. From what I can tell, DAB effort is orthogonal to this change as it doesn't require the `AddressBook` object to be a part of the Merkle tree.

**Review by edward-swirldslabs — APPROVED** [review]

**Review by cody-littley — APPROVED** [review]

**Review by edward-swirldslabs — APPROVED** [review]

**Review by iwsimon — APPROVED** [review]
LGTM.

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM!

**Pull request merged**
