### PR TITLE
Add support for microbenchmarking to the Gradle build

### LINKED ISSUE #3370: Add support for building and running microbenchmarks with Gradle
Each subproject in the Gradle build should have a configuration called "jmh" which can be used for microbenchmarks. Any JMH benchmarks in that source directory should be run when `./gradlew jmh` is executed. In addition, you should be able to run the benchmarks from IntelliJ, and you should be able to run just the specific benchmark that you want even from Gradle. You should also be able to supply configuration overrides to the benchmark when run from Gradle.

### PR DESCRIPTION
**Pull request by rbair23**
Closes #3370. Adds a new task called "jmh" for executing micro benchmarks. Only `hedera-node` implements it today. Microbenchmarks are in`src/jmh/java`. They are not run as part of `./gradlew build`. They must be run specially. They take time to execute so they are not part of CI/CD (although maybe could be run nightly. Maybe).

### CODE REVIEW

**Review by tinker-michaelj — DISMISSED** [review]
LGTM! Given removal of _benchmarks/_ module from Maven build, I guess we should always run Gradle build at least once before PR to make sure we didn't break anything. 😁

**Comment by tinker-michaelj** [comment]
@rbair23 Does `./gradlew jmh` work as expected for you? Something seems broken with `ConstructableRegistry` classpath scanning when running via Gradle; e.g, in the `SizeLimitedStorageBench.simulateContractTransaction` benchmark:
```
com.swirlds.common.constructable.ConstructableRegistryException: Lambda constructor threw an Exception: null
        at com.swirlds.common.constructable.ConstructableRegistry.registerConstructable(ConstructableRegistry.java:156)
        at com.hedera.hashgraph.setup.Constructables.registerForVirtualMap(Constructables.java:99)
        at com.hedera.hashgraph.SizeLimitedStorageBench.registerConstructables(SizeLimitedStorageBench.java:127)
```

**Comment by rbair23** [comment]
> @rbair23 Does `./gradlew jmh` work as expected for you? Something seems broken with `ConstructableRegistry` classpath scanning when running via Gradle; e.g, in the `SizeLimitedStorageBench.simulateContractTransaction` benchmark:
> 
> ```
> com.swirlds.common.constructable.ConstructableRegistryException: Lambda constructor threw an Exception: null
>         at com.swirlds.common.constructable.ConstructableRegistry.registerConstructable(ConstructableRegistry.java:156)
>         at com.hedera.hashgraph.setup.Constructables.registerForVirtualMap(Constructables.java:99)
>         at com.hedera.hashgraph.SizeLimitedStorageBench.registerConstructables(SizeLimitedStorageBench.java:127)
> ```

Hmmm.... it did run for me. Will check again.

**Comment by rbair23** [comment]
I can confirm I'm getting the same error. Will debug.

**Comment by rbair23** [comment]
> I can confirm I'm getting the same error. Will debug.

I think it has something to do with modules / protections at the Java level. The [code in question in VirtualNodeCache (line 120)](https://github.com/swirlds/swirlds-platform/blob/3455ba305abf6947d4850072fb631143d1c070f2/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/cache/VirtualNodeCache.java) is trying to get a logger from the LogManager and explicitly passes in the class. But LogManager gets null, and ends up trying to figure out the calling class via sun reflection classes:

```private static Class<?> callerClass(final Class<?> clazz) {
        if (clazz != null) {
            return clazz;
        } else {
            Class<?> candidate = StackLocatorUtil.getCallerClass(3);
            if (candidate == null) {
                throw new UnsupportedOperationException("No class provided, and an appropriate one cannot be found.");
            } else {
                return candidate;
            }
        }
    }```

It can only get to the exception if clazz is null, but it isn't. So somehow there is a protection in play where the JDK is lying to log4j because they're in different modules or something along those lines. My best guess ATM.

**Comment by tinker-michaelj** [comment]
> > I can confirm I'm getting the same error. Will debug.
> 
> I think it has something to do with modules / protections at the Java level. The [code in question in VirtualNodeCache (line 120)](https://github.com/swirlds/swirlds-platform/blob/3455ba305abf6947d4850072fb631143d1c070f2/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/cache/VirtualNodeCache.java) is trying to get a logger from the LogManager and explicitly passes in the class. But LogManager gets null, and ends up trying to figure out the calling class via sun reflection classes:
> 
> ```
> private static Class<?> callerClass(final Class<?> clazz) {
>         if (clazz != null) {
>             return clazz;
>         } else {
>             Class<?> candidate = StackLocatorUtil.getCallerClass(3);
>             if (candidate == null) {
>                 throw new UnsupportedOperationException("No class provided, and an appropriate one cannot be found.");
>             } else {
>                 return candidate;
>             }
>         }
>     }
> ```
> 
> It can only get to the exception if clazz is null, but it isn't. So somehow there is a protection in play where the JDK is lying to log4j because they're in different modules or something along those lines. My best guess ATM.

I just remembered, we need [`Multi-Release: true`](https://github.com/hashgraph/hedera-services/pull/3447) in the JMH JAR manifest.

**Review by tinker-michaelj — APPROVED** [review]
LGTM!

**Pull request merged**
