### PR TITLE
updated hip-16

### PR DESCRIPTION
**Pull request by SimiHunjan**
**Summary of the change**:
Added content

### CODE REVIEW

**Comment by abhishek-hedera** [comment]
Links to a similar [PR](https://github.com/hashgraph/hedera-services/pull/1228)

**Comment by SimiHunjan** [comment]
It similar PR, but I believe the edits made are different between the two.

**Review by qnswirlds — COMMENTED** [review]
@SimiHunjan, this file has been moved to the HIP repo
https://github.com/hashgraph/hedera-improvement-proposal/blob/master/HIP/hip-16.md
Please close this PR. Thank you!

**Comment by tinker-michaelj** [comment]
HIP no longer in Services repo.

**Pull request closed without merging**
