### PR TITLE
fix: stabilize `SysDelSysUndelSpec`

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Description**:
 - Update `release/0.50` to use `submitModifiedWithFixedPayer()` with some privileged operations that will not have the expected statuses using a "civilian" payer account.

### CODE REVIEW

**Review by mhess-swl — DISMISSED** [review]

**Comment by david-bakin-sl** [comment]
This is not a cherry pick of a full commit, but the code comes from 30bab441 in `develop`.

**Review by david-bakin-sl — APPROVED** [review]
LGTM! (confirmed cherry pick of relevant chunks from 30bab441 in `develop`.

**Review by david-bakin-sl — DISMISSED** [review]
LGTM again (after fixing spotless)

**Review by david-bakin-sl — APPROVED** [review]
LGTM!  Tests pass too, always a plus ...

**Pull request merged**
