### PR TITLE
old files removed from repo

### LINKED ISSUE #4241: Check "old" folders and files for usage
The repo contains several folders and files for that the usage is currently not clear. We should check for all that files if they can be deleted. Otherwise we should check if we can move them to a better place (for example not directly in the root folder) and document them

### Files in root directory
- `data` folder
- `image-utils` folder
- `run` folder
- `test-tools` folder
- `.dockerignore`
- `.env`
- `codecov.yml`
- `compose-build.sh`
- `docker-compose.yml` (maybe we can create a `docker` folder in root)
- `Dockerfile`
- `logback.xml`

### Files in `happy-utils` module
- `add-copyright.sh`
- `copyright.txt`
- `gen-proto-docs.sh`
- `HAPI.html`

### Files in `hedera-node` module
- `configuration` folder
- `data` folder
- `forensics` folder
- `.env`
- `config.txt`
- `deprecations.md`
- `log4j2.xml`
- `log4j2-prod.xml`
- `settings.txt`

### Files in `hedera-mono-service` module
- `data` folder
- `database` folder
- `hedera-node` folder
- `recordStreamTest` folder
- `swirlds-tmp` folder
- `temp` folder

part of epic https://github.com/hashgraph/hedera-services/issues/4243

### PR DESCRIPTION
**Pull request by hendrikebbers**
I have not found any usage for any of the removed files. Maybe @tinker-michaelj @Neeharika-Sompalli @nathanklick or @JeffreyDallas know / use some of them?

Closes #4241

### CODE REVIEW

**Comment by rbair23** [comment]
The `wait-for-it` script was an essential part of the docker image, I'm not sure if it is still used?

**Comment by mhess-swl** [comment]
Are we really not using any of these scripts?

**Comment by hendrikebbers** [comment]
> The `wait-for-it` script was an essential part of the docker image, I'm not sure if it is still used?

@rbair23 I searched for it and have not found it.


> Are we really not using any of these scripts?

@mhess-swl I have not found any usage of the scripts. But I never used them and therefore others need to say if they are still needed / used




> If we aren't using them that's fine, but some of these still look useful

@mhess-swl but in that case we should store them somewhere else (central place in repo maybe).

**Comment by mhess-swl** [comment]
> @mhess-swl but in that case we should store them somewhere else (central place in repo maybe).

@hendrikebbers Sure, I'm fine with that. @Neeharika-Sompalli @tinker-michaelj what would you like to do with these scripts?

**Comment by JeffreyDallas** [comment]
not sure about files under **run** directory, need @nathanklick  to confirm it

**Review by nathanklick — APPROVED** [review]
I agree with Hendrik that these files can be safely deleted.

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM ! Need Michael's confirmation if any of these files are used.

**Comment by hendrikebbers** [comment]
@tinker-michaelj can you please have a final look?

**Review by nathanklick — APPROVED** [review]

**Review by Neeharika-Sompalli — COMMENTED** [review]
LGTM !

**Comment by tinker-michaelj** [comment]
They're not **critical** to keep in the repo, but I'll definitely keep a local copy of:
 - _run/reset-data-saved-from.sh_: Handy for setting up a local network from a well-known state.
 - _run/gen-explicit-fee-schedules.py_: In the (always-painful) scenario that a HAPI operation's canonical price changes, we need this Python script to regenerate the JSON resources used by the public fee tool.

**Comment by mhess-swl** [comment]
> They're not **critical** to keep in the repo, but I'll definitely keep a local copy of:
> 
> * _run/reset-data-saved-from.sh_: Handy for setting up a local network from a well-known state.
> * _run/gen-explicit-fee-schedules.py_: In the (always-painful) scenario that a HAPI operation's canonical price changes, we need this Python script to regenerate the JSON resources used by the public fee tool.

Sounds like those two are worth keeping in the repo

**Review by nathanklick — APPROVED** [review]

**Review by tinker-michaelj — APPROVED** [review]
LGTM!

**Pull request merged**
