### PR TITLE
Replace nextRelease folder with 4 new configuration folders

### LINKED ISSUE #1133: Update configuration organization and process
We currently have a single location for configuration that is used in devops managed deployments at https://github.com/hashgraph/hedera-services/tree/master/hedera-node/configuration/nextRelease This is currently intended to be updated to reflect configuration that will be applied on the next release. However most of these configurations can now be updated outside of release cycle and often are. The single configuration set provided also makes it difficult to keep track of what changes have been applied to which networks. With all of this in mind, we would like to change the organization and process to support the following:

Replace the "nextRelease" configuration folder with 4 new configuration folders:
  - "preprod" - reflects current configurations applied to preproduction environments. The configuration in this location should be updated prior to configuration updates being applied to a preproduction network via transaction. DevOps deployments will pull configurations directly from this location to use when initializing or resetting a preproduction environment.
  - "previewnet" - reflects current configurations applied to previewnet. Configuration in this location should be updated prior to applying configuration updates to previewnet via transaction. DevOps deployments will pull configurations directly from this location when new releases are deployed to previewnet. These deployments always reset the network state, so these configurations will be used to initialize the new network state
  - "testnet" - reflects current configurations applied to stable testnet. As with above, this should be updated before applying updates to the network via transaction. On the occasions that the testnet is reset, these configurations will be used to initialize the new network state
  - "mainnet" - reflects current configurations applied to mainnet. As with above, this should be updated prior to applying updates to mainnet via transaction. The configurations here will be part of deployments when upgrading the mainnet release, but will not apply in this scenario since they are only used on initializing new network state, which will not occur for mainnet

This approach will mean more PRs for configuration changes as they are applied through the networks, but will provide the benefit of ensuring configuration changes are not lost on networks that reset state, and will also provide an accurate reference for current configurations on each network

### PR DESCRIPTION
**Pull request by anighanta**
Replace nextRelease folder with 4 new configuration folders,
one for each of mainnet, testnet, preprod and previewnet networks

Signed-off-by: anighanta <anirudh.ghanta@hedera.com>

**Related issue(s)**:
Closes #1133 

**Summary of the change**:
Renamed `nextRelease` folder to `mainnet`
Created `preprod`, `testnet` and `previewnet` folders similar to that of `mainnet`

**External impacts**:
None.

**Applicable documentation**
- [ ] Javadoc
- [ ] HAPI protobuf comments
- [ ] README

### CODE REVIEW

**Review by tannerjfco — DISMISSED** [review]
This looks good to me, thanks for making these changes 👍

**Review by ljianghedera — DISMISSED** [review]
LGTM

**Comment by anighanta** [comment]
As https://github.com/hashgraph/hedera-services/pull/1076 is merged. Can we merge this too now ?
@tannerjfco @dp-h @Neeharika-Sompalli ?

**Comment by Neeharika-Sompalli** [comment]
> As #1076 is merged. Can we merge this too now ?
> @tannerjfco @dp-h @Neeharika-Sompalli ?

@anighanta  Checked all log4j's are updated with the latest pattern and Changes look good to me. Thanks

**Review by Neeharika-Sompalli — APPROVED** [review]

**Comment by anighanta** [comment]
@tannerjfco @dp-h can we merge this configuration change ?

**Comment by anighanta** [comment]
Closing this PR. This config change is no longer needed

**Review by tannerjfco — APPROVED** [review]

**Pull request merged**
