### PR TITLE
Adding @HapiTestSuite to all suites

### PR DESCRIPTION
**Pull request by vtronkov**
**Description**:
Adding @HapiTestSuite to all suites we have

**Related issue(s)**:

_No issue created_

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by MiroslavGatsanoga — APPROVED** [review]

**Review by netopyr — CHANGES_REQUESTED** [review]
Please double-check if `AutoRenewConfigChoices` needs the `@HapiTestSuite` annotation.

**Comment by netopyr** [comment]
After further thought, let's ignore all test suites that extend `LoadTest` for now. These are performance tests, which we should ignore until the functionality is correct. Can you please change that? Sorry for the extra work. I was not aware of these tests.

**Comment by vtronkov** [comment]
> After further thought, let's ignore all test suites that extend `LoadTest` for now. These are performance tests, which we should ignore until the functionality is correct. Can you please change that? Sorry for the extra work. I was not aware of these tests.

No worries 😄 Fixed

**Review by netopyr — APPROVED** [review]
LGTM

**Review by mhess-swl — APPROVED** [review]

**Pull request merged**
