### PR TITLE
chore: remove unused mono code

### LINKED ISSUE #13827: Remove Mono code that is not used anymore

### LINKED ISSUE #13944: Remove Mono dependencies from fee calculation

### LINKED ISSUE #13945: Remove Schema 49 (mono) migration

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Description**:
 - Closes #13827 
 - Closes #13944 
 - Closes #13945

### CODE REVIEW

**Review by lukelee-sl — DISMISSED** [review]
LGTM

**Review by Neeharika-Sompalli — DISMISSED** [review]
LGTM! Thanks @tinker-michaelj !But there are conflicts

**Review by jeromy-cannon — APPROVED** [review]

**Review by alittley — APPROVED** [review]
Approved to placate github, but I don't see any platform owned files in the diff. So approved wrt these 0 files

**Review by Neeharika-Sompalli — APPROVED** [review]

**Review by lukelee-sl — APPROVED** [review]
LGTM

**Review by kimbor — APPROVED** [review]
Boom!

**Pull request merged**
