### PR TITLE
chore: Replace jetbrains annotations with Spotbugs

### LINKED ISSUE #3349: Replace jetbrains annotations with standard javax annotations
### Problem

We have a mixture of jetbrains specific annotations and javax annotations.

### Solution

Replace all org.jetbrains.annotations with the corresponding ones from javax annotations.

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by thomas-swirlds-labs**
**Description**:

Remove all org.jetbrains.annotations and replace them with the corresponding Spotbugs ones as standard.

**Related issue(s)**:

Fixes #3349 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by david-bakin-sl — DISMISSED** [review]
LGTM.  

A very nice addition to this PR would be to:
* Update `docs/hedera-java-style-guide` to explicitly mention that we only use the annotations from spotbugs (it has a section "4.8.5 Annotations"), and
* Update `docs/intellij-quickstart` to recommend adding both `javax.annotation` and `org.jetbrains.annotations` to the IntelliJ setting `Editor/General/Auto Import/Exclude from auto-import and completion`.

image

**Comment by david-bakin-sl** [comment]
(BTW, reason for suggesting the documentation changes above is that this error is still happening - see for example https://github.com/hashgraph/hedera-services/pull/14514#discussion_r1699210064 (where the error isn't in the PR submitted there but in a feature branch it is modifying).

**Review by mhess-swl — APPROVED** [review]

**Comment by thomas-swirlds-labs** [comment]
> LGTM.
> 
> A very nice addition to this PR would be to:
> 
> * Update `docs/hedera-java-style-guide` to explicitly mention that we only use the annotations from spotbugs (it has a section "4.8.5 Annotations"), and
> * Update `docs/intellij-quickstart` to recommend adding both `javax.annotation` and `org.jetbrains.annotations` to the IntelliJ setting `Editor/General/Auto Import/Exclude from auto-import and completion`.
> 
> image

Have included recommendations for markdown. Thanks @david-bakin-sl 🚀

**Review by david-bakin-sl — COMMENTED** [review]
LGTM!

**Review by david-bakin-sl — APPROVED** [review]
LGTM

**Review by mhess-swl — APPROVED** [review]

**Review by iwsimon — APPROVED** [review]
LGTM. Thanks @thomas-swirlds-labs

**Review by nathanklick — APPROVED** [review]

**Pull request merged**
