### PR TITLE
requires static used for com.github.spotbugs.annotations

### PR DESCRIPTION
**Pull request by hendrikebbers**
the annotations should not be on the class path at runtime

### CODE REVIEW

**Review by nathanklick — CHANGES_REQUESTED** [review]
Integration tests are failing and needs to be diagnosed.

**Comment by hendrikebbers** [comment]
@nathanklick looks like this was only a temporary issues that happened after the last update of the branch.

**Review by Neeharika-Sompalli — APPROVED** [review]

**Review by rbair23 — APPROVED** [review]

**Review by nathanklick — APPROVED** [review]

**Comment by mhess-swl** [comment]
Merge conflicts need resolved

**Comment by hendrikebbers** [comment]
closed since it is solved now in https://github.com/hashgraph/hedera-services/pull/7088#pullrequestreview-1481474394

**Pull request closed without merging**
