### PR TITLE
Skeleton Mindmap

### LINKED ISSUE #5108: Add skeleton mindmap documentation for the platform
It is difficult to understand the platform as a whole, what its components, or how key concepts relate to one another. Skeleton documentation should be added and filled in with detailed documentation.

### PR DESCRIPTION
**Pull request by poulok**
**Description**:

This PR adds 
* A skeleton mindmap of concepts with links
* Component diagrams
* Configuration markdown

**Related issue(s)**:

closes #5108 

**Notes for reviewer**:

To use, checkout the branch and open the `mindmap-node.html` file. From there, click around to other diagrams and markdown files.

### CODE REVIEW

**Comment by alittley** [comment]
Some thoughts (they don't necessarily have to be addressed in this PR, if we just want to get the baseline merged):
- every chart should have a title, since it can otherwise be difficult to know where you are
- some of the existing linkages seem to be unintentional
    - The `State` chart has a `State` bubble, which links back to the main chart Screenshot 2023-03-03 at 11 52 02 AM
    - The `Infrastructure` chart has an `Infrastructure` bubble, which links back to the main chart Screenshot 2023-03-03 at 11 55 17 AM
- Bubbles being repeated in multiple diagrams makes it easy to get lost
    - for example, a `Gossip` bubble exists in the main chart. If I click that `Gossip` bubble, I'm led to another chart that *also* has a `Gossip` bubble. If I click the `Consensus` bubble, that chart has a `Gossip` bubble too. 
    - I think it would be best if a `Gossip` bubble exists *only* in the main chart. If I step down into `Consensus`, I should have to step back up before being able to click into `Gossip`
- it would be convenient if there was a way to know if a link goes to markdown, or if it goes to somewhere else in the graph. if I'm traversing the graph, unexpectedly being led to markdown is unhelpful
- a sidebar feature that shows you where the current diagram exists in the diagram hierarchy would be very helpful (not for this PR, of course)

**Review by cody-littley — APPROVED** [review]
I'm a big fan of the components diagram, I think there is a lot of useful information here. I like how I can click into the StateManagement and see an expanded view.

The mindmap graph is confusing to me... I'm not sure what information I supposed to extract from it. Let's say I wanted to jump to documentation on a particular part of the system -- I feel like I could spend several minutes trying to figure out where it is in the mindmap. If it were up to me, I'd make the top level of the chart be the component diagram, and nest all information below that.

**Comment by poulok** [comment]
> I'm a big fan of the components diagram, I think there is a lot of useful information here. I like how I can click into the StateManagement and see an expanded view.
> 
> The mindmap graph is confusing to me... I'm not sure what information I supposed to extract from it. Let's say I wanted to jump to documentation on a particular part of the system -- I feel like I could spend several minutes trying to figure out where it is in the mindmap. If it were up to me, I'd make the top level of the chart be the component diagram, and nest all information below that.

We can organize sub folders inside `docs` to help you get to the diagram you want right away. The problem with having the component diagram be the main diagram that you use to drill down into is that it is very specific to the hashgraph team. The work that the base and data teams do and the concepts that are important to those teams are not well represented there. I also think it is more useful for someone new to the system to see how the different concepts are related to each other which is difficult to understand with just a component diagram.

**Comment by poulok** [comment]
> Some thoughts (they don't necessarily have to be addressed in this PR, if we just want to get the baseline merged):
> 
> * every chart should have a title, since it can otherwise be difficult to know where you are
> * some of the existing linkages seem to be unintentional
>   
>   * The `State` chart has a `State` bubble, which links back to the main chart Screenshot 2023-03-03 at 11 52 02 AM
>   * The `Infrastructure` chart has an `Infrastructure` bubble, which links back to the main chart Screenshot 2023-03-03 at 11 55 17 AM
> * Bubbles being repeated in multiple diagrams makes it easy to get lost
>   
>   * for example, a `Gossip` bubble exists in the main chart. If I click that `Gossip` bubble, I'm led to another chart that _also_ has a `Gossip` bubble. If I click the `Consensus` bubble, that chart has a `Gossip` bubble too.
>   * I think it would be best if a `Gossip` bubble exists _only_ in the main chart. If I step down into `Consensus`, I should have to step back up before being able to click into `Gossip`
> * it would be convenient if there was a way to know if a link goes to markdown, or if it goes to somewhere else in the graph. if I'm traversing the graph, unexpectedly being led to markdown is unhelpful
> * a sidebar feature that shows you where the current diagram exists in the diagram hierarchy would be very helpful (not for this PR, of course)

* I made the bubble that represents each mindmap chart bold, light gray, and larger than the other bubbles
* Removed unintentional links
* I moved bubbles on each chart that are related concepts but do not decompose the title bubble above the title bubble. Hopefully that will help.
* The team voted for a graph format rather than a tree, so we will stick with this format.
* Yes, that would be nice. But I don't think DrawIO supports that, and it would be too much work to create a custom widget or create a composite widget and keep it up to date.

**Review by cody-littley — APPROVED** [review]

**Review by alittley — APPROVED** [review]

**Review by edward-swirldslabs — APPROVED** [review]
Does the location of `/blob/develop/` matter in the URLs?  
- (Infrastructure image --> configuration node) 
-- currently: https://github.com/hashgraph/hedera-services/platform-sdk/docs/configuration/blob/develop/README.MD
-- should it be: https://github.com/hashgraph/hedera-services/blob/develop/platform-sdk/docs/configuration/README.MD
-- Example of working URL: https://github.com/hashgraph/hedera-services/blob/develop/platform-sdk/docs/PlatformThreads.drawio.svg

**Pull request merged**
