### PR TITLE
chore: Config records moved to correct modules

### PR DESCRIPTION
**Pull request by hendrikebbers**
Fixes https://github.com/hashgraph/hedera-services/issues/10283

### CODE REVIEW

**Comment by hendrikebbers** [comment]
@lpetrovic05 @cody-littley For some configs I had no idea what the best package in platform module is. If you want some config records to be moved just add it :)

**Review by povolev15 — APPROVED** [review]
LGTM

**Review by cody-littley — DISMISSED** [review]

**Review by edward-swirldslabs — DISMISSED** [review]

**Review by lpetrovic05 — APPROVED** [review]

**Review by povolev15 — DISMISSED** [review]
LGTM

**Review by cody-littley — DISMISSED** [review]

**Comment by cody-littley** [comment]
> or some configs I had no idea what the best package in platform module is. If you want some config records to be moved just add it :)

I'm ok with the current plan, we can always adjust in the future.

**Review by edward-swirldslabs — DISMISSED** [review]

**Review by jeromy-cannon — DISMISSED** [review]

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM !

**Review by cody-littley — DISMISSED** [review]

**Review by mxtartaglia-sl — DISMISSED** [review]

**Review by mxtartaglia-sl — APPROVED** [review]

**Review by jeromy-cannon — APPROVED** [review]

**Review by edward-swirldslabs — APPROVED** [review]

**Review by rbair23 — APPROVED** [review]

**Pull request merged**
