### PR TITLE
00988: Removes extra QueueThread from RecordStreamManager

### LINKED ISSUE #988: Remove runningHashQueueThread from RecordStreamManager
**Summary**
`RecordStreamManager` is [using a `QueueThread`](https://github.com/hashgraph/hedera-services/blob/ed9a920a9ebc3aec664d4f628896c7308a62f7e9/hedera-node/src/main/java/com/hedera/services/stream/RecordStreamManager.java#L139) between the `HashCalculatorForStream` and `RunningHashCalculatorForStream`. This `QueueThread` was added to improve performance but in the next Swirlds SDK release, it won't be necessary.

**Possible resolution**
Remove the extra `QueueThread`, and run tests to validate against the current SDK 0.8.1 and current develop branch which will become 0.8.2

### PR DESCRIPTION
**Pull request by cesaragv**
**Related issue(s)**:
Closes #988

**Summary of the change**:
*Performance results*
Crypto-Basic-Performance-10k-46m:
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1611160463074600
Crypto-Restart-1.5k-10m:
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1611179508083700
Misc-UpdateNode-1-6m   against 0.8.2
Misc-Update-1-5m  against 0.8.2
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1611334794022600
Crypto-Restart-1.5k-10m against 0.8.2
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1611339739025000

### CODE REVIEW

**Review by qnswirlds — COMMENTED** [review]
@cesaragv, as mentioned in #988, does next Swirlds SDK release mean v0.8.1?

**Comment by cesaragv** [comment]
> @cesaragv, as mentioned in #988, does next Swirlds SDK release mean v0.8.1?

@qnswirlds current is v0.8.1 and next is 0.8.2

**Comment by qnswirlds** [comment]
> > @cesaragv, as mentioned in #988, does next Swirlds SDK release mean v0.8.1?
> 
> @qnswirlds current is v0.8.1 and next is 0.8.2

@cesaragv, so for all the test results you put in the PR description, especially the 10k TPS performance test, were they with SDK 0.8.2?

**Comment by cesaragv** [comment]
> > > @cesaragv, as mentioned in #988, does next Swirlds SDK release mean v0.8.1?
> > 
> > 
> > @qnswirlds current is v0.8.1 and next is 0.8.2
> 
> @cesaragv, so for all the test results you put in the PR description, especially the 10k TPS performance test, were they with SDK 0.8.2?

@qnswirlds yes

**Review by Neeharika-Sompalli — APPROVED** [review]

**Pull request merged**
