### PR TITLE
Ci enable 2143

### PR DESCRIPTION
**Pull request by anighanta**
N/A

### CODE REVIEW

**Comment by anighanta** [comment]
Pending merge of https://github.com/hashgraph/hedera-services/pull/2226

**Review by MarcKriguerAtHedera — APPROVED** [review]
Very long PR - but LGTM.

**Review by abhishek-hedera — APPROVED** [review]
LGTM

**Comment by tinker-michaelj** [comment]
Unlikely this PR is still applicable.

**Pull request closed without merging**
