### PR TITLE
chore: fix the record mismatch for `prng` transactions

### LINKED ISSUE #11166: Replay events from round 160257004 and validate record files for differential testing
Replay events from round 160257004 and validate record files for differential testing.
issues found
Mismatched field counts  (expected but not find [tokenTransferLists]) between expected receipt {
Mismatched values, expected '56', got '31' - Matching field 'prng_number'  ==> expected: <56> but was: <31>
Mismatched values, expected '69', got '81' - Matching field 'prng_number'  ==> expected: <69> but was: <81>
Mismatched values, expected '88', got '66' - Matching field 'prng_number'  ==> expected: <88> but was: <66>

### LINKED ISSUE #11212: Replay events from round `160073757` and validate record files (differential testing)

### PR DESCRIPTION
**Pull request by Neeharika-Sompalli**
Fixes #11166 
Fixes https://github.com/hashgraph/hedera-services/issues/11146
Fixes #11212

- Changes pseudoRandomNumber generation in `UtilPrng` handler to be same as in mono-service
- Updates running hashes each time we handle transaction irrespective of currentRecordFileWriter being null at genesis or restart

### CODE REVIEW

**Review by mhess-swl — DISMISSED** [review]

**Review by povolev15 — APPROVED** [review]
LGTM

**Review by iwsimon — DISMISSED** [review]
LGTM. Thanks @Neeharika-Sompalli

**Review by tinker-michaelj — DISMISSED** [review]
LGTM, tyvm @Neeharika-Sompalli !

**Review by povolev15 — APPROVED** [review]
LGTM

**Review by iwsimon — APPROVED** [review]

**Review by povolev15 — DISMISSED** [review]

**Review by iwsimon — DISMISSED** [review]
LGTM, thanks @Neeharika-Sompalli

**Review by povolev15 — DISMISSED** [review]

**Review by tinker-michaelj — APPROVED** [review]
LGTM!

**Review by iwsimon — APPROVED** [review]

**Pull request merged**
