### PR TITLE
chore:  cherry pick #11013

### PR DESCRIPTION
**Pull request by lukelee-sl**
**Description**:
Cherry pick #11013

### CODE REVIEW

**Review by tinker-michaelj — DISMISSED** [review]
LGTM, ty @lukelee-sl

**Review by Nana-EC — APPROVED** [review]

**Review by tinker-michaelj — APPROVED** [review]
LGTM

**Review by tinker-michaelj — DISMISSED** [review]
LGTM!

**Review by tinker-michaelj — APPROVED** [review]
LGTM, thanks @lukelee-sl !

**Review by Nana-EC — APPROVED** [review]

**Pull request merged**
