### PR TITLE
fix: update the Schema class import statement

### LINKED ISSUE #13418: The "Schema" link in javadoc in ReadableKVState refers to the wrong Schema class
## 🆕🐥 First Timers Only

This issue is reserved for people who have never contributed to [Hedera](https://hedera.com) or any open source project in general.
We know that creating a pull request (PR) is a major barrier for new contributors.
The goal of this issue and all other issues labeled by [**'good first issue'**](https://github.com/issues?q=is%3Aopen+is%3Aissue+org%3Ahashgraph+archived%3Afalse+label%3A%22good+first+issue%22+) is to help you make your first contribution to Hedera.

## 👾 Description of the issue

In class `ReadableKVState` you can find the following JavaDoc:

```
/**
* Gets the "state key" that uniquely identifies this {@link ReadableKVState} within the {@link
* Schema} which are scoped to the service implementation. The key is therefore not globally
* unique, only unique within the service implementation itself.
*
* <p>The call is idempotent, always returning the same value. It must never return null.
*
* @return The state key. This will never be null, and will always be the same value for an
*     instance of {@link ReadableKVState}.
*/
```

This comment refers to the wrong `Schema` class.

### Steps to reproduce

See in the import. It should be the state Schema class, not the PBJ schema.

### Proposed Solution:

The import for the `Schema` class needs to be changed.

## 📋 Step by step guide to do a contribution

If you have never contributed to an open source project at GitHub, the following step-by-step guide will introduce you to the workflow. More information and concrete samples for shell commands for each step can be found in our [CONTRIBUTING.md](https://github.com/hashgraph/.github/blob/main/CONTRIBUTING.md) file.
A more detailed general documentation of the GitHub PR workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [ ] **Claim this issue:** Comment below that you are interested in working on the issue
- [ ] **Wait for assignment:** A community member with the given rights will add you as an assignee of the issue
- [ ] **Fork the repository:** You can do that in GitHub (by simply clicking the 'fork' button).
- [ ] **Check out the forked repository**
- [ ] **Create a feature branch** for the issue. We do not have a hard naming definition for branches but it is best practice to prefix the branch name with the issue id.
- [ ] **Solve the issue** in your branch.
- [ ] **Commit your changes:** Here, it is needed to add `sign-off` information to the commit to accept the "Developer Certificate of Origin" (https://developercertificate.org). More details can be found in our [CONTRIBUTING.md](https://github.com/hashgraph/.github/blob/main/CONTRIBUTING.md)
- [ ] **Start a Pull Request (PR)**: We have a pattern for naming pull requests that a GitHub Action checks. We use that pattern to support the creation of automatic release notes.
- [ ] **Check GitHub Actions:** Several GitHub Actions will be triggered automatically for each PR. If a GitHub Action fails and you do not understand the cause of that error do not hesitate to add a comment to the PR and ask the Hedera developer community for support.
- [ ] **Wait for reviews:** Members of the Hedera developer community will review your PR. If a reviewer finds any missing pieces or a problem, he or she will start a discussion with you and describe the next steps for solving the problem.
- [ ] **You did it 🎉:** We will merge the fix in the develop branch. Thanks for being part of the Hedera community as an open-source contributor ❤️

## 🎉 Contribute to Hacktoberfest

Solve this issue as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) event and get a chance to receive cool goodies like a T-Shirt. 🎽

## 🤔 Additional Information

If you have any questions, just ask us directly in this issue by adding a comment. You can join our community chat at [Discord](https://hedera.com/discord). A general manual about open-source contributions can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

### PR DESCRIPTION
**Pull request by albertopasqualetto**
**Description**:

Add correct Schema class.

**Related issue(s)**:

Fixes #13418

**Notes for reviewer**:

It guess it should be correct.

**Checklist**

- [] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by hendrikebbers — DISMISSED** [review]

**Review by nathanklick — DISMISSED** [review]

**Comment by albertopasqualetto** [comment]
@poulok yes sure, I just did it

**Review by timo0 — APPROVED** [review]

**Comment by timo0** [comment]
Thanks @albertopasqualetto for your contribution! LGTM

**Review by petreze — COMMENTED** [review]
The `codacy` failure in `Unit Tests` check might be because the PR is coming from a fork of services repo and the user not being part of Hedera organization..
The test that failed in `HAPI Tests (Misc)` check was flaky and it passed after several reruns

**Comment by timo0** [comment]
@petreze Can we then please overwrite the check and merge this regardless?

**Pull request merged**
